// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package bot_state

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// IDLE is a BotState of type IDLE.
	IDLE BotState = iota
	// AWAITING_DIALOG_MESSAGE is a BotState of type AWAITING_DIALOG_MESSAGE.
	AWAITING_DIALOG_MESSAGE
	// AWAITING_POST_CONTENT is a BotState of type AWAITING_POST_CONTENT.
	AWAITING_POST_CONTENT
	// ADMIN_MODE is a BotState of type ADMIN_MODE.
	ADMIN_MODE
)

var ErrInvalidBotState = errors.New("not a valid BotState")

const _BotStateName = "IDLEAWAITING_DIALOG_MESSAGEAWAITING_POST_CONTENTADMIN_MODE"

// BotStateValues returns a list of the values for BotState
func BotStateValues() []BotState {
	return []BotState{
		IDLE,
		AWAITING_DIALOG_MESSAGE,
		AWAITING_POST_CONTENT,
		ADMIN_MODE,
	}
}

var _BotStateMap = map[BotState]string{
	IDLE:                    _BotStateName[0:4],
	AWAITING_DIALOG_MESSAGE: _BotStateName[4:27],
	AWAITING_POST_CONTENT:   _BotStateName[27:48],
	ADMIN_MODE:              _BotStateName[48:58],
}

// String implements the Stringer interface.
func (x BotState) String() string {
	if str, ok := _BotStateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("BotState(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x BotState) IsValid() bool {
	_, ok := _BotStateMap[x]
	return ok
}

var _BotStateValue = map[string]BotState{
	_BotStateName[0:4]:   IDLE,
	_BotStateName[4:27]:  AWAITING_DIALOG_MESSAGE,
	_BotStateName[27:48]: AWAITING_POST_CONTENT,
	_BotStateName[48:58]: ADMIN_MODE,
}

// ParseBotState attempts to convert a string to a BotState.
func ParseBotState(name string) (BotState, error) {
	if x, ok := _BotStateValue[name]; ok {
		return x, nil
	}
	return BotState(0), fmt.Errorf("%s is %w", name, ErrInvalidBotState)
}

// MustParseBotState converts a string to a BotState, and panics if is not valid.
func MustParseBotState(name string) BotState {
	val, err := ParseBotState(name)
	if err != nil {
		panic(err)
	}
	return val
}

var errBotStateNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *BotState) Scan(value interface{}) (err error) {
	if value == nil {
		*x = BotState(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = BotState(v)
	case string:
		*x, err = ParseBotState(v)
	case []byte:
		*x, err = ParseBotState(string(v))
	case BotState:
		*x = v
	case int:
		*x = BotState(v)
	case *BotState:
		if v == nil {
			return errBotStateNilPtr
		}
		*x = *v
	case uint:
		*x = BotState(v)
	case uint64:
		*x = BotState(v)
	case *int:
		if v == nil {
			return errBotStateNilPtr
		}
		*x = BotState(*v)
	case *int64:
		if v == nil {
			return errBotStateNilPtr
		}
		*x = BotState(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = BotState(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errBotStateNilPtr
		}
		*x = BotState(*v)
	case *uint:
		if v == nil {
			return errBotStateNilPtr
		}
		*x = BotState(*v)
	case *uint64:
		if v == nil {
			return errBotStateNilPtr
		}
		*x = BotState(*v)
	case *string:
		if v == nil {
			return errBotStateNilPtr
		}
		*x, err = ParseBotState(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x BotState) Value() (driver.Value, error) {
	return x.String(), nil
}
