package deal_status

// ENUM(
// DRAFT,
// PENDING,
// DISCUSSION,
// IN_PROGRESS,
// AWAITING_APPROVAL,
// AWAITING_APPROVAL_TIME,
// AWAITING_PUBLICATION,
// PUBLISHED,
// CANCELED,
// EXPIRED,
// TERMS_VIOLATED,
// COMPLETED,
// ERR_PUBLISH,
// ERR_BAD_TARGET,
// )
type DealStatus int
