// Code generated by ent, DO NOT EDIT.

package deal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the deal type in the database.
	Label = "deal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldAdvertiserCustomerID holds the string denoting the advertiser_customer_id field in the database.
	FieldAdvertiserCustomerID = "advertiser_customer_id"
	// FieldChannelManagerID holds the string denoting the channel_manager_id field in the database.
	FieldChannelManagerID = "channel_manager_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStatusUpdatedAt holds the string denoting the status_updated_at field in the database.
	FieldStatusUpdatedAt = "status_updated_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldTargetType holds the string denoting the target_type field in the database.
	FieldTargetType = "target_type"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldPublicationTime holds the string denoting the publication_time field in the database.
	FieldPublicationTime = "publication_time"
	// FieldTopDeadline holds the string denoting the top_deadline field in the database.
	FieldTopDeadline = "top_deadline"
	// FieldCommonDeadline holds the string denoting the common_deadline field in the database.
	FieldCommonDeadline = "common_deadline"
	// FieldTonPrice holds the string denoting the ton_price field in the database.
	FieldTonPrice = "ton_price"
	// FieldBalanceRefunded holds the string denoting the balance_refunded field in the database.
	FieldBalanceRefunded = "balance_refunded"
	// FieldChannelPostIds holds the string denoting the channel_post_ids field in the database.
	FieldChannelPostIds = "channel_post_ids"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// EdgeAdvertiser holds the string denoting the advertiser edge name in mutations.
	EdgeAdvertiser = "advertiser"
	// EdgeChannelManager holds the string denoting the channel_manager edge name in mutations.
	EdgeChannelManager = "channel_manager"
	// Table holds the table name of the deal in the database.
	Table = "deals"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "deals"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
	// AdvertiserTable is the table that holds the advertiser relation/edge.
	AdvertiserTable = "deals"
	// AdvertiserInverseTable is the table name for the Customer entity.
	// It exists in this package in order to avoid circular dependency with the "customer" package.
	AdvertiserInverseTable = "customers"
	// AdvertiserColumn is the table column denoting the advertiser relation/edge.
	AdvertiserColumn = "advertiser_customer_id"
	// ChannelManagerTable is the table that holds the channel_manager relation/edge.
	ChannelManagerTable = "deals"
	// ChannelManagerInverseTable is the table name for the Customer entity.
	// It exists in this package in order to avoid circular dependency with the "customer" package.
	ChannelManagerInverseTable = "customers"
	// ChannelManagerColumn is the table column denoting the channel_manager relation/edge.
	ChannelManagerColumn = "channel_manager_id"
)

// Columns holds all SQL columns for deal fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldChannelID,
	FieldAdvertiserCustomerID,
	FieldChannelManagerID,
	FieldType,
	FieldStatus,
	FieldStatusUpdatedAt,
	FieldExpiresAt,
	FieldTargetType,
	FieldTarget,
	FieldPublicationTime,
	FieldTopDeadline,
	FieldCommonDeadline,
	FieldTonPrice,
	FieldBalanceRefunded,
	FieldChannelPostIds,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
	// DefaultStatusUpdatedAt holds the default value on creation for the "status_updated_at" field.
	DefaultStatusUpdatedAt func() time.Time
	// DefaultTargetType holds the default value on creation for the "target_type" field.
	DefaultTargetType string
	// DefaultTarget holds the default value on creation for the "target" field.
	DefaultTarget map[string]interface{}
	// TonPriceValidator is a validator for the "ton_price" field. It is called by the builders before save.
	TonPriceValidator func(float64) error
	// DefaultBalanceRefunded holds the default value on creation for the "balance_refunded" field.
	DefaultBalanceRefunded bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Deal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByAdvertiserCustomerID orders the results by the advertiser_customer_id field.
func ByAdvertiserCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdvertiserCustomerID, opts...).ToFunc()
}

// ByChannelManagerID orders the results by the channel_manager_id field.
func ByChannelManagerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelManagerID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStatusUpdatedAt orders the results by the status_updated_at field.
func ByStatusUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusUpdatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByTargetType orders the results by the target_type field.
func ByTargetType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetType, opts...).ToFunc()
}

// ByPublicationTime orders the results by the publication_time field.
func ByPublicationTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicationTime, opts...).ToFunc()
}

// ByTopDeadline orders the results by the top_deadline field.
func ByTopDeadline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopDeadline, opts...).ToFunc()
}

// ByCommonDeadline orders the results by the common_deadline field.
func ByCommonDeadline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommonDeadline, opts...).ToFunc()
}

// ByTonPrice orders the results by the ton_price field.
func ByTonPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTonPrice, opts...).ToFunc()
}

// ByBalanceRefunded orders the results by the balance_refunded field.
func ByBalanceRefunded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceRefunded, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}

// ByAdvertiserField orders the results by advertiser field.
func ByAdvertiserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdvertiserStep(), sql.OrderByField(field, opts...))
	}
}

// ByChannelManagerField orders the results by channel_manager field.
func ByChannelManagerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelManagerStep(), sql.OrderByField(field, opts...))
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
func newAdvertiserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdvertiserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AdvertiserTable, AdvertiserColumn),
	)
}
func newChannelManagerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelManagerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelManagerTable, ChannelManagerColumn),
	)
}
