// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BotState is the predicate function for botstate builders.
type BotState func(*sql.Selector)

// Brief is the predicate function for brief builders.
type Brief func(*sql.Selector)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// CustomerBrief is the predicate function for customerbrief builders.
type CustomerBrief func(*sql.Selector)

// CustomerChannel is the predicate function for customerchannel builders.
type CustomerChannel func(*sql.Selector)

// Deal is the predicate function for deal builders.
type Deal func(*sql.Selector)

// IndexerState is the predicate function for indexerstate builders.
type IndexerState func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)
