// Code generated by ent, DO NOT EDIT.

package customerbrief

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldUpdatedAt, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldCustomerID, v))
}

// BriefID applies equality check predicate on the "brief_id" field. It's identical to BriefIDEQ.
func BriefID(v uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldBriefID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldLTE(FieldUpdatedAt, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNotIn(FieldCustomerID, vs...))
}

// BriefIDEQ applies the EQ predicate on the "brief_id" field.
func BriefIDEQ(v uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldEQ(FieldBriefID, v))
}

// BriefIDNEQ applies the NEQ predicate on the "brief_id" field.
func BriefIDNEQ(v uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNEQ(FieldBriefID, v))
}

// BriefIDIn applies the In predicate on the "brief_id" field.
func BriefIDIn(vs ...uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldIn(FieldBriefID, vs...))
}

// BriefIDNotIn applies the NotIn predicate on the "brief_id" field.
func BriefIDNotIn(vs ...uuid.UUID) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.FieldNotIn(FieldBriefID, vs...))
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.CustomerBrief {
	return predicate.CustomerBrief(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.CustomerBrief {
	return predicate.CustomerBrief(func(s *sql.Selector) {
		step := newCustomerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBrief applies the HasEdge predicate on the "brief" edge.
func HasBrief() predicate.CustomerBrief {
	return predicate.CustomerBrief(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BriefTable, BriefColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBriefWith applies the HasEdge predicate on the "brief" edge with a given conditions (other predicates).
func HasBriefWith(preds ...predicate.Brief) predicate.CustomerBrief {
	return predicate.CustomerBrief(func(s *sql.Selector) {
		step := newBriefStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomerBrief) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomerBrief) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomerBrief) predicate.CustomerBrief {
	return predicate.CustomerBrief(sql.NotPredicates(p))
}
