// Code generated by ent, DO NOT EDIT.

package indexerstate

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldLTE(FieldID, id))
}

// ServiceName applies equality check predicate on the "service_name" field. It's identical to ServiceNameEQ.
func ServiceName(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldEQ(FieldServiceName, v))
}

// LastSeqno applies equality check predicate on the "last_seqno" field. It's identical to LastSeqnoEQ.
func LastSeqno(v uint64) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldEQ(FieldLastSeqno, v))
}

// ServiceNameEQ applies the EQ predicate on the "service_name" field.
func ServiceNameEQ(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldEQ(FieldServiceName, v))
}

// ServiceNameNEQ applies the NEQ predicate on the "service_name" field.
func ServiceNameNEQ(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldNEQ(FieldServiceName, v))
}

// ServiceNameIn applies the In predicate on the "service_name" field.
func ServiceNameIn(vs ...string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldIn(FieldServiceName, vs...))
}

// ServiceNameNotIn applies the NotIn predicate on the "service_name" field.
func ServiceNameNotIn(vs ...string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldNotIn(FieldServiceName, vs...))
}

// ServiceNameGT applies the GT predicate on the "service_name" field.
func ServiceNameGT(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldGT(FieldServiceName, v))
}

// ServiceNameGTE applies the GTE predicate on the "service_name" field.
func ServiceNameGTE(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldGTE(FieldServiceName, v))
}

// ServiceNameLT applies the LT predicate on the "service_name" field.
func ServiceNameLT(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldLT(FieldServiceName, v))
}

// ServiceNameLTE applies the LTE predicate on the "service_name" field.
func ServiceNameLTE(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldLTE(FieldServiceName, v))
}

// ServiceNameContains applies the Contains predicate on the "service_name" field.
func ServiceNameContains(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldContains(FieldServiceName, v))
}

// ServiceNameHasPrefix applies the HasPrefix predicate on the "service_name" field.
func ServiceNameHasPrefix(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldHasPrefix(FieldServiceName, v))
}

// ServiceNameHasSuffix applies the HasSuffix predicate on the "service_name" field.
func ServiceNameHasSuffix(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldHasSuffix(FieldServiceName, v))
}

// ServiceNameEqualFold applies the EqualFold predicate on the "service_name" field.
func ServiceNameEqualFold(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldEqualFold(FieldServiceName, v))
}

// ServiceNameContainsFold applies the ContainsFold predicate on the "service_name" field.
func ServiceNameContainsFold(v string) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldContainsFold(FieldServiceName, v))
}

// LastSeqnoEQ applies the EQ predicate on the "last_seqno" field.
func LastSeqnoEQ(v uint64) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldEQ(FieldLastSeqno, v))
}

// LastSeqnoNEQ applies the NEQ predicate on the "last_seqno" field.
func LastSeqnoNEQ(v uint64) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldNEQ(FieldLastSeqno, v))
}

// LastSeqnoIn applies the In predicate on the "last_seqno" field.
func LastSeqnoIn(vs ...uint64) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldIn(FieldLastSeqno, vs...))
}

// LastSeqnoNotIn applies the NotIn predicate on the "last_seqno" field.
func LastSeqnoNotIn(vs ...uint64) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldNotIn(FieldLastSeqno, vs...))
}

// LastSeqnoGT applies the GT predicate on the "last_seqno" field.
func LastSeqnoGT(v uint64) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldGT(FieldLastSeqno, v))
}

// LastSeqnoGTE applies the GTE predicate on the "last_seqno" field.
func LastSeqnoGTE(v uint64) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldGTE(FieldLastSeqno, v))
}

// LastSeqnoLT applies the LT predicate on the "last_seqno" field.
func LastSeqnoLT(v uint64) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldLT(FieldLastSeqno, v))
}

// LastSeqnoLTE applies the LTE predicate on the "last_seqno" field.
func LastSeqnoLTE(v uint64) predicate.IndexerState {
	return predicate.IndexerState(sql.FieldLTE(FieldLastSeqno, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IndexerState) predicate.IndexerState {
	return predicate.IndexerState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IndexerState) predicate.IndexerState {
	return predicate.IndexerState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IndexerState) predicate.IndexerState {
	return predicate.IndexerState(sql.NotPredicates(p))
}
