// Code generated by ent, DO NOT EDIT.

package channel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldUpdatedAt, v))
}

// TgID applies equality check predicate on the "tg_id" field. It's identical to TgIDEQ.
func TgID(v int64) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgID, v))
}

// TgUsername applies equality check predicate on the "tg_username" field. It's identical to TgUsernameEQ.
func TgUsername(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgUsername, v))
}

// TgName applies equality check predicate on the "tg_name" field. It's identical to TgNameEQ.
func TgName(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgName, v))
}

// TgDescription applies equality check predicate on the "tg_description" field. It's identical to TgDescriptionEQ.
func TgDescription(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgDescription, v))
}

// TgPicture applies equality check predicate on the "tg_picture" field. It's identical to TgPictureEQ.
func TgPicture(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgPicture, v))
}

// Commentary applies equality check predicate on the "commentary" field. It's identical to CommentaryEQ.
func Commentary(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldCommentary, v))
}

// IsListed applies equality check predicate on the "is_listed" field. It's identical to IsListedEQ.
func IsListed(v bool) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldIsListed, v))
}

// StatsUpdatedAt applies equality check predicate on the "stats_updated_at" field. It's identical to StatsUpdatedAtEQ.
func StatsUpdatedAt(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldStatsUpdatedAt, v))
}

// Subscribers applies equality check predicate on the "subscribers" field. It's identical to SubscribersEQ.
func Subscribers(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldSubscribers, v))
}

// PremiumSubscribers applies equality check predicate on the "premium_subscribers" field. It's identical to PremiumSubscribersEQ.
func PremiumSubscribers(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldPremiumSubscribers, v))
}

// MedianPostViews applies equality check predicate on the "median_post_views" field. It's identical to MedianPostViewsEQ.
func MedianPostViews(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldMedianPostViews, v))
}

// AvgPostViews applies equality check predicate on the "avg_post_views" field. It's identical to AvgPostViewsEQ.
func AvgPostViews(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldAvgPostViews, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldStatus, v))
}

// MainLanguage applies equality check predicate on the "main_language" field. It's identical to MainLanguageEQ.
func MainLanguage(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldMainLanguage, v))
}

// RestrictedFrom applies equality check predicate on the "restricted_from" field. It's identical to RestrictedFromEQ.
func RestrictedFrom(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldRestrictedFrom, v))
}

// RestrictedTill applies equality check predicate on the "restricted_till" field. It's identical to RestrictedTillEQ.
func RestrictedTill(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldRestrictedTill, v))
}

// NotificationsOn applies equality check predicate on the "notifications_on" field. It's identical to NotificationsOnEQ.
func NotificationsOn(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldNotificationsOn, v))
}

// FirstPostDate applies equality check predicate on the "first_post_date" field. It's identical to FirstPostDateEQ.
func FirstPostDate(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldFirstPostDate, v))
}

// TotalPosts applies equality check predicate on the "total_posts" field. It's identical to TotalPostsEQ.
func TotalPosts(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTotalPosts, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldUpdatedAt, v))
}

// TgIDEQ applies the EQ predicate on the "tg_id" field.
func TgIDEQ(v int64) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgID, v))
}

// TgIDNEQ applies the NEQ predicate on the "tg_id" field.
func TgIDNEQ(v int64) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldTgID, v))
}

// TgIDIn applies the In predicate on the "tg_id" field.
func TgIDIn(vs ...int64) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldTgID, vs...))
}

// TgIDNotIn applies the NotIn predicate on the "tg_id" field.
func TgIDNotIn(vs ...int64) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldTgID, vs...))
}

// TgIDGT applies the GT predicate on the "tg_id" field.
func TgIDGT(v int64) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldTgID, v))
}

// TgIDGTE applies the GTE predicate on the "tg_id" field.
func TgIDGTE(v int64) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldTgID, v))
}

// TgIDLT applies the LT predicate on the "tg_id" field.
func TgIDLT(v int64) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldTgID, v))
}

// TgIDLTE applies the LTE predicate on the "tg_id" field.
func TgIDLTE(v int64) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldTgID, v))
}

// TgUsernameEQ applies the EQ predicate on the "tg_username" field.
func TgUsernameEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgUsername, v))
}

// TgUsernameNEQ applies the NEQ predicate on the "tg_username" field.
func TgUsernameNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldTgUsername, v))
}

// TgUsernameIn applies the In predicate on the "tg_username" field.
func TgUsernameIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldTgUsername, vs...))
}

// TgUsernameNotIn applies the NotIn predicate on the "tg_username" field.
func TgUsernameNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldTgUsername, vs...))
}

// TgUsernameGT applies the GT predicate on the "tg_username" field.
func TgUsernameGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldTgUsername, v))
}

// TgUsernameGTE applies the GTE predicate on the "tg_username" field.
func TgUsernameGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldTgUsername, v))
}

// TgUsernameLT applies the LT predicate on the "tg_username" field.
func TgUsernameLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldTgUsername, v))
}

// TgUsernameLTE applies the LTE predicate on the "tg_username" field.
func TgUsernameLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldTgUsername, v))
}

// TgUsernameContains applies the Contains predicate on the "tg_username" field.
func TgUsernameContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldTgUsername, v))
}

// TgUsernameHasPrefix applies the HasPrefix predicate on the "tg_username" field.
func TgUsernameHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldTgUsername, v))
}

// TgUsernameHasSuffix applies the HasSuffix predicate on the "tg_username" field.
func TgUsernameHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldTgUsername, v))
}

// TgUsernameIsNil applies the IsNil predicate on the "tg_username" field.
func TgUsernameIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldTgUsername))
}

// TgUsernameNotNil applies the NotNil predicate on the "tg_username" field.
func TgUsernameNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldTgUsername))
}

// TgUsernameEqualFold applies the EqualFold predicate on the "tg_username" field.
func TgUsernameEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldTgUsername, v))
}

// TgUsernameContainsFold applies the ContainsFold predicate on the "tg_username" field.
func TgUsernameContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldTgUsername, v))
}

// TgNameEQ applies the EQ predicate on the "tg_name" field.
func TgNameEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgName, v))
}

// TgNameNEQ applies the NEQ predicate on the "tg_name" field.
func TgNameNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldTgName, v))
}

// TgNameIn applies the In predicate on the "tg_name" field.
func TgNameIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldTgName, vs...))
}

// TgNameNotIn applies the NotIn predicate on the "tg_name" field.
func TgNameNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldTgName, vs...))
}

// TgNameGT applies the GT predicate on the "tg_name" field.
func TgNameGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldTgName, v))
}

// TgNameGTE applies the GTE predicate on the "tg_name" field.
func TgNameGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldTgName, v))
}

// TgNameLT applies the LT predicate on the "tg_name" field.
func TgNameLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldTgName, v))
}

// TgNameLTE applies the LTE predicate on the "tg_name" field.
func TgNameLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldTgName, v))
}

// TgNameContains applies the Contains predicate on the "tg_name" field.
func TgNameContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldTgName, v))
}

// TgNameHasPrefix applies the HasPrefix predicate on the "tg_name" field.
func TgNameHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldTgName, v))
}

// TgNameHasSuffix applies the HasSuffix predicate on the "tg_name" field.
func TgNameHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldTgName, v))
}

// TgNameIsNil applies the IsNil predicate on the "tg_name" field.
func TgNameIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldTgName))
}

// TgNameNotNil applies the NotNil predicate on the "tg_name" field.
func TgNameNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldTgName))
}

// TgNameEqualFold applies the EqualFold predicate on the "tg_name" field.
func TgNameEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldTgName, v))
}

// TgNameContainsFold applies the ContainsFold predicate on the "tg_name" field.
func TgNameContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldTgName, v))
}

// TgDescriptionEQ applies the EQ predicate on the "tg_description" field.
func TgDescriptionEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgDescription, v))
}

// TgDescriptionNEQ applies the NEQ predicate on the "tg_description" field.
func TgDescriptionNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldTgDescription, v))
}

// TgDescriptionIn applies the In predicate on the "tg_description" field.
func TgDescriptionIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldTgDescription, vs...))
}

// TgDescriptionNotIn applies the NotIn predicate on the "tg_description" field.
func TgDescriptionNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldTgDescription, vs...))
}

// TgDescriptionGT applies the GT predicate on the "tg_description" field.
func TgDescriptionGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldTgDescription, v))
}

// TgDescriptionGTE applies the GTE predicate on the "tg_description" field.
func TgDescriptionGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldTgDescription, v))
}

// TgDescriptionLT applies the LT predicate on the "tg_description" field.
func TgDescriptionLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldTgDescription, v))
}

// TgDescriptionLTE applies the LTE predicate on the "tg_description" field.
func TgDescriptionLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldTgDescription, v))
}

// TgDescriptionContains applies the Contains predicate on the "tg_description" field.
func TgDescriptionContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldTgDescription, v))
}

// TgDescriptionHasPrefix applies the HasPrefix predicate on the "tg_description" field.
func TgDescriptionHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldTgDescription, v))
}

// TgDescriptionHasSuffix applies the HasSuffix predicate on the "tg_description" field.
func TgDescriptionHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldTgDescription, v))
}

// TgDescriptionIsNil applies the IsNil predicate on the "tg_description" field.
func TgDescriptionIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldTgDescription))
}

// TgDescriptionNotNil applies the NotNil predicate on the "tg_description" field.
func TgDescriptionNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldTgDescription))
}

// TgDescriptionEqualFold applies the EqualFold predicate on the "tg_description" field.
func TgDescriptionEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldTgDescription, v))
}

// TgDescriptionContainsFold applies the ContainsFold predicate on the "tg_description" field.
func TgDescriptionContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldTgDescription, v))
}

// TgPictureEQ applies the EQ predicate on the "tg_picture" field.
func TgPictureEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTgPicture, v))
}

// TgPictureNEQ applies the NEQ predicate on the "tg_picture" field.
func TgPictureNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldTgPicture, v))
}

// TgPictureIn applies the In predicate on the "tg_picture" field.
func TgPictureIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldTgPicture, vs...))
}

// TgPictureNotIn applies the NotIn predicate on the "tg_picture" field.
func TgPictureNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldTgPicture, vs...))
}

// TgPictureGT applies the GT predicate on the "tg_picture" field.
func TgPictureGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldTgPicture, v))
}

// TgPictureGTE applies the GTE predicate on the "tg_picture" field.
func TgPictureGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldTgPicture, v))
}

// TgPictureLT applies the LT predicate on the "tg_picture" field.
func TgPictureLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldTgPicture, v))
}

// TgPictureLTE applies the LTE predicate on the "tg_picture" field.
func TgPictureLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldTgPicture, v))
}

// TgPictureContains applies the Contains predicate on the "tg_picture" field.
func TgPictureContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldTgPicture, v))
}

// TgPictureHasPrefix applies the HasPrefix predicate on the "tg_picture" field.
func TgPictureHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldTgPicture, v))
}

// TgPictureHasSuffix applies the HasSuffix predicate on the "tg_picture" field.
func TgPictureHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldTgPicture, v))
}

// TgPictureIsNil applies the IsNil predicate on the "tg_picture" field.
func TgPictureIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldTgPicture))
}

// TgPictureNotNil applies the NotNil predicate on the "tg_picture" field.
func TgPictureNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldTgPicture))
}

// TgPictureEqualFold applies the EqualFold predicate on the "tg_picture" field.
func TgPictureEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldTgPicture, v))
}

// TgPictureContainsFold applies the ContainsFold predicate on the "tg_picture" field.
func TgPictureContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldTgPicture, v))
}

// CommentaryEQ applies the EQ predicate on the "commentary" field.
func CommentaryEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldCommentary, v))
}

// CommentaryNEQ applies the NEQ predicate on the "commentary" field.
func CommentaryNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldCommentary, v))
}

// CommentaryIn applies the In predicate on the "commentary" field.
func CommentaryIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldCommentary, vs...))
}

// CommentaryNotIn applies the NotIn predicate on the "commentary" field.
func CommentaryNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldCommentary, vs...))
}

// CommentaryGT applies the GT predicate on the "commentary" field.
func CommentaryGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldCommentary, v))
}

// CommentaryGTE applies the GTE predicate on the "commentary" field.
func CommentaryGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldCommentary, v))
}

// CommentaryLT applies the LT predicate on the "commentary" field.
func CommentaryLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldCommentary, v))
}

// CommentaryLTE applies the LTE predicate on the "commentary" field.
func CommentaryLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldCommentary, v))
}

// CommentaryContains applies the Contains predicate on the "commentary" field.
func CommentaryContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldCommentary, v))
}

// CommentaryHasPrefix applies the HasPrefix predicate on the "commentary" field.
func CommentaryHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldCommentary, v))
}

// CommentaryHasSuffix applies the HasSuffix predicate on the "commentary" field.
func CommentaryHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldCommentary, v))
}

// CommentaryIsNil applies the IsNil predicate on the "commentary" field.
func CommentaryIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldCommentary))
}

// CommentaryNotNil applies the NotNil predicate on the "commentary" field.
func CommentaryNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldCommentary))
}

// CommentaryEqualFold applies the EqualFold predicate on the "commentary" field.
func CommentaryEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldCommentary, v))
}

// CommentaryContainsFold applies the ContainsFold predicate on the "commentary" field.
func CommentaryContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldCommentary, v))
}

// IsListedEQ applies the EQ predicate on the "is_listed" field.
func IsListedEQ(v bool) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldIsListed, v))
}

// IsListedNEQ applies the NEQ predicate on the "is_listed" field.
func IsListedNEQ(v bool) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldIsListed, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldTags))
}

// StatsUpdatedAtEQ applies the EQ predicate on the "stats_updated_at" field.
func StatsUpdatedAtEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldStatsUpdatedAt, v))
}

// StatsUpdatedAtNEQ applies the NEQ predicate on the "stats_updated_at" field.
func StatsUpdatedAtNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldStatsUpdatedAt, v))
}

// StatsUpdatedAtIn applies the In predicate on the "stats_updated_at" field.
func StatsUpdatedAtIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldStatsUpdatedAt, vs...))
}

// StatsUpdatedAtNotIn applies the NotIn predicate on the "stats_updated_at" field.
func StatsUpdatedAtNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldStatsUpdatedAt, vs...))
}

// StatsUpdatedAtGT applies the GT predicate on the "stats_updated_at" field.
func StatsUpdatedAtGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldStatsUpdatedAt, v))
}

// StatsUpdatedAtGTE applies the GTE predicate on the "stats_updated_at" field.
func StatsUpdatedAtGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldStatsUpdatedAt, v))
}

// StatsUpdatedAtLT applies the LT predicate on the "stats_updated_at" field.
func StatsUpdatedAtLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldStatsUpdatedAt, v))
}

// StatsUpdatedAtLTE applies the LTE predicate on the "stats_updated_at" field.
func StatsUpdatedAtLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldStatsUpdatedAt, v))
}

// StatsIsNil applies the IsNil predicate on the "stats" field.
func StatsIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldStats))
}

// StatsNotNil applies the NotNil predicate on the "stats" field.
func StatsNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldStats))
}

// PricesIsNil applies the IsNil predicate on the "prices" field.
func PricesIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldPrices))
}

// PricesNotNil applies the NotNil predicate on the "prices" field.
func PricesNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldPrices))
}

// SubscribersEQ applies the EQ predicate on the "subscribers" field.
func SubscribersEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldSubscribers, v))
}

// SubscribersNEQ applies the NEQ predicate on the "subscribers" field.
func SubscribersNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldSubscribers, v))
}

// SubscribersIn applies the In predicate on the "subscribers" field.
func SubscribersIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldSubscribers, vs...))
}

// SubscribersNotIn applies the NotIn predicate on the "subscribers" field.
func SubscribersNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldSubscribers, vs...))
}

// SubscribersGT applies the GT predicate on the "subscribers" field.
func SubscribersGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldSubscribers, v))
}

// SubscribersGTE applies the GTE predicate on the "subscribers" field.
func SubscribersGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldSubscribers, v))
}

// SubscribersLT applies the LT predicate on the "subscribers" field.
func SubscribersLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldSubscribers, v))
}

// SubscribersLTE applies the LTE predicate on the "subscribers" field.
func SubscribersLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldSubscribers, v))
}

// SubscribersIsNil applies the IsNil predicate on the "subscribers" field.
func SubscribersIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldSubscribers))
}

// SubscribersNotNil applies the NotNil predicate on the "subscribers" field.
func SubscribersNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldSubscribers))
}

// PremiumSubscribersEQ applies the EQ predicate on the "premium_subscribers" field.
func PremiumSubscribersEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldPremiumSubscribers, v))
}

// PremiumSubscribersNEQ applies the NEQ predicate on the "premium_subscribers" field.
func PremiumSubscribersNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldPremiumSubscribers, v))
}

// PremiumSubscribersIn applies the In predicate on the "premium_subscribers" field.
func PremiumSubscribersIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldPremiumSubscribers, vs...))
}

// PremiumSubscribersNotIn applies the NotIn predicate on the "premium_subscribers" field.
func PremiumSubscribersNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldPremiumSubscribers, vs...))
}

// PremiumSubscribersGT applies the GT predicate on the "premium_subscribers" field.
func PremiumSubscribersGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldPremiumSubscribers, v))
}

// PremiumSubscribersGTE applies the GTE predicate on the "premium_subscribers" field.
func PremiumSubscribersGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldPremiumSubscribers, v))
}

// PremiumSubscribersLT applies the LT predicate on the "premium_subscribers" field.
func PremiumSubscribersLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldPremiumSubscribers, v))
}

// PremiumSubscribersLTE applies the LTE predicate on the "premium_subscribers" field.
func PremiumSubscribersLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldPremiumSubscribers, v))
}

// PremiumSubscribersIsNil applies the IsNil predicate on the "premium_subscribers" field.
func PremiumSubscribersIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldPremiumSubscribers))
}

// PremiumSubscribersNotNil applies the NotNil predicate on the "premium_subscribers" field.
func PremiumSubscribersNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldPremiumSubscribers))
}

// MedianPostViewsEQ applies the EQ predicate on the "median_post_views" field.
func MedianPostViewsEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldMedianPostViews, v))
}

// MedianPostViewsNEQ applies the NEQ predicate on the "median_post_views" field.
func MedianPostViewsNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldMedianPostViews, v))
}

// MedianPostViewsIn applies the In predicate on the "median_post_views" field.
func MedianPostViewsIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldMedianPostViews, vs...))
}

// MedianPostViewsNotIn applies the NotIn predicate on the "median_post_views" field.
func MedianPostViewsNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldMedianPostViews, vs...))
}

// MedianPostViewsGT applies the GT predicate on the "median_post_views" field.
func MedianPostViewsGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldMedianPostViews, v))
}

// MedianPostViewsGTE applies the GTE predicate on the "median_post_views" field.
func MedianPostViewsGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldMedianPostViews, v))
}

// MedianPostViewsLT applies the LT predicate on the "median_post_views" field.
func MedianPostViewsLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldMedianPostViews, v))
}

// MedianPostViewsLTE applies the LTE predicate on the "median_post_views" field.
func MedianPostViewsLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldMedianPostViews, v))
}

// MedianPostViewsIsNil applies the IsNil predicate on the "median_post_views" field.
func MedianPostViewsIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldMedianPostViews))
}

// MedianPostViewsNotNil applies the NotNil predicate on the "median_post_views" field.
func MedianPostViewsNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldMedianPostViews))
}

// AvgPostViewsEQ applies the EQ predicate on the "avg_post_views" field.
func AvgPostViewsEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldAvgPostViews, v))
}

// AvgPostViewsNEQ applies the NEQ predicate on the "avg_post_views" field.
func AvgPostViewsNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldAvgPostViews, v))
}

// AvgPostViewsIn applies the In predicate on the "avg_post_views" field.
func AvgPostViewsIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldAvgPostViews, vs...))
}

// AvgPostViewsNotIn applies the NotIn predicate on the "avg_post_views" field.
func AvgPostViewsNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldAvgPostViews, vs...))
}

// AvgPostViewsGT applies the GT predicate on the "avg_post_views" field.
func AvgPostViewsGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldAvgPostViews, v))
}

// AvgPostViewsGTE applies the GTE predicate on the "avg_post_views" field.
func AvgPostViewsGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldAvgPostViews, v))
}

// AvgPostViewsLT applies the LT predicate on the "avg_post_views" field.
func AvgPostViewsLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldAvgPostViews, v))
}

// AvgPostViewsLTE applies the LTE predicate on the "avg_post_views" field.
func AvgPostViewsLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldAvgPostViews, v))
}

// AvgPostViewsIsNil applies the IsNil predicate on the "avg_post_views" field.
func AvgPostViewsIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldAvgPostViews))
}

// AvgPostViewsNotNil applies the NotNil predicate on the "avg_post_views" field.
func AvgPostViewsNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldAvgPostViews))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldStatus, v))
}

// MainLanguageEQ applies the EQ predicate on the "main_language" field.
func MainLanguageEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldMainLanguage, v))
}

// MainLanguageNEQ applies the NEQ predicate on the "main_language" field.
func MainLanguageNEQ(v string) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldMainLanguage, v))
}

// MainLanguageIn applies the In predicate on the "main_language" field.
func MainLanguageIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldMainLanguage, vs...))
}

// MainLanguageNotIn applies the NotIn predicate on the "main_language" field.
func MainLanguageNotIn(vs ...string) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldMainLanguage, vs...))
}

// MainLanguageGT applies the GT predicate on the "main_language" field.
func MainLanguageGT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldMainLanguage, v))
}

// MainLanguageGTE applies the GTE predicate on the "main_language" field.
func MainLanguageGTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldMainLanguage, v))
}

// MainLanguageLT applies the LT predicate on the "main_language" field.
func MainLanguageLT(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldMainLanguage, v))
}

// MainLanguageLTE applies the LTE predicate on the "main_language" field.
func MainLanguageLTE(v string) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldMainLanguage, v))
}

// MainLanguageContains applies the Contains predicate on the "main_language" field.
func MainLanguageContains(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContains(FieldMainLanguage, v))
}

// MainLanguageHasPrefix applies the HasPrefix predicate on the "main_language" field.
func MainLanguageHasPrefix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasPrefix(FieldMainLanguage, v))
}

// MainLanguageHasSuffix applies the HasSuffix predicate on the "main_language" field.
func MainLanguageHasSuffix(v string) predicate.Channel {
	return predicate.Channel(sql.FieldHasSuffix(FieldMainLanguage, v))
}

// MainLanguageIsNil applies the IsNil predicate on the "main_language" field.
func MainLanguageIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldMainLanguage))
}

// MainLanguageNotNil applies the NotNil predicate on the "main_language" field.
func MainLanguageNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldMainLanguage))
}

// MainLanguageEqualFold applies the EqualFold predicate on the "main_language" field.
func MainLanguageEqualFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldEqualFold(FieldMainLanguage, v))
}

// MainLanguageContainsFold applies the ContainsFold predicate on the "main_language" field.
func MainLanguageContainsFold(v string) predicate.Channel {
	return predicate.Channel(sql.FieldContainsFold(FieldMainLanguage, v))
}

// RestrictedFromEQ applies the EQ predicate on the "restricted_from" field.
func RestrictedFromEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldRestrictedFrom, v))
}

// RestrictedFromNEQ applies the NEQ predicate on the "restricted_from" field.
func RestrictedFromNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldRestrictedFrom, v))
}

// RestrictedFromIn applies the In predicate on the "restricted_from" field.
func RestrictedFromIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldRestrictedFrom, vs...))
}

// RestrictedFromNotIn applies the NotIn predicate on the "restricted_from" field.
func RestrictedFromNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldRestrictedFrom, vs...))
}

// RestrictedFromGT applies the GT predicate on the "restricted_from" field.
func RestrictedFromGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldRestrictedFrom, v))
}

// RestrictedFromGTE applies the GTE predicate on the "restricted_from" field.
func RestrictedFromGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldRestrictedFrom, v))
}

// RestrictedFromLT applies the LT predicate on the "restricted_from" field.
func RestrictedFromLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldRestrictedFrom, v))
}

// RestrictedFromLTE applies the LTE predicate on the "restricted_from" field.
func RestrictedFromLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldRestrictedFrom, v))
}

// RestrictedTillEQ applies the EQ predicate on the "restricted_till" field.
func RestrictedTillEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldRestrictedTill, v))
}

// RestrictedTillNEQ applies the NEQ predicate on the "restricted_till" field.
func RestrictedTillNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldRestrictedTill, v))
}

// RestrictedTillIn applies the In predicate on the "restricted_till" field.
func RestrictedTillIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldRestrictedTill, vs...))
}

// RestrictedTillNotIn applies the NotIn predicate on the "restricted_till" field.
func RestrictedTillNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldRestrictedTill, vs...))
}

// RestrictedTillGT applies the GT predicate on the "restricted_till" field.
func RestrictedTillGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldRestrictedTill, v))
}

// RestrictedTillGTE applies the GTE predicate on the "restricted_till" field.
func RestrictedTillGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldRestrictedTill, v))
}

// RestrictedTillLT applies the LT predicate on the "restricted_till" field.
func RestrictedTillLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldRestrictedTill, v))
}

// RestrictedTillLTE applies the LTE predicate on the "restricted_till" field.
func RestrictedTillLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldRestrictedTill, v))
}

// RestrictionReasonEQ applies the EQ predicate on the "restriction_reason" field.
func RestrictionReasonEQ(v RestrictionReason) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldRestrictionReason, v))
}

// RestrictionReasonNEQ applies the NEQ predicate on the "restriction_reason" field.
func RestrictionReasonNEQ(v RestrictionReason) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldRestrictionReason, v))
}

// RestrictionReasonIn applies the In predicate on the "restriction_reason" field.
func RestrictionReasonIn(vs ...RestrictionReason) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldRestrictionReason, vs...))
}

// RestrictionReasonNotIn applies the NotIn predicate on the "restriction_reason" field.
func RestrictionReasonNotIn(vs ...RestrictionReason) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldRestrictionReason, vs...))
}

// NotificationsOnEQ applies the EQ predicate on the "notifications_on" field.
func NotificationsOnEQ(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldNotificationsOn, v))
}

// NotificationsOnNEQ applies the NEQ predicate on the "notifications_on" field.
func NotificationsOnNEQ(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldNotificationsOn, v))
}

// NotificationsOnIn applies the In predicate on the "notifications_on" field.
func NotificationsOnIn(vs ...float64) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldNotificationsOn, vs...))
}

// NotificationsOnNotIn applies the NotIn predicate on the "notifications_on" field.
func NotificationsOnNotIn(vs ...float64) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldNotificationsOn, vs...))
}

// NotificationsOnGT applies the GT predicate on the "notifications_on" field.
func NotificationsOnGT(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldNotificationsOn, v))
}

// NotificationsOnGTE applies the GTE predicate on the "notifications_on" field.
func NotificationsOnGTE(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldNotificationsOn, v))
}

// NotificationsOnLT applies the LT predicate on the "notifications_on" field.
func NotificationsOnLT(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldNotificationsOn, v))
}

// NotificationsOnLTE applies the LTE predicate on the "notifications_on" field.
func NotificationsOnLTE(v float64) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldNotificationsOn, v))
}

// FirstPostDateEQ applies the EQ predicate on the "first_post_date" field.
func FirstPostDateEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldFirstPostDate, v))
}

// FirstPostDateNEQ applies the NEQ predicate on the "first_post_date" field.
func FirstPostDateNEQ(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldFirstPostDate, v))
}

// FirstPostDateIn applies the In predicate on the "first_post_date" field.
func FirstPostDateIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldFirstPostDate, vs...))
}

// FirstPostDateNotIn applies the NotIn predicate on the "first_post_date" field.
func FirstPostDateNotIn(vs ...time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldFirstPostDate, vs...))
}

// FirstPostDateGT applies the GT predicate on the "first_post_date" field.
func FirstPostDateGT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldFirstPostDate, v))
}

// FirstPostDateGTE applies the GTE predicate on the "first_post_date" field.
func FirstPostDateGTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldFirstPostDate, v))
}

// FirstPostDateLT applies the LT predicate on the "first_post_date" field.
func FirstPostDateLT(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldFirstPostDate, v))
}

// FirstPostDateLTE applies the LTE predicate on the "first_post_date" field.
func FirstPostDateLTE(v time.Time) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldFirstPostDate, v))
}

// FirstPostDateIsNil applies the IsNil predicate on the "first_post_date" field.
func FirstPostDateIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldFirstPostDate))
}

// FirstPostDateNotNil applies the NotNil predicate on the "first_post_date" field.
func FirstPostDateNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldFirstPostDate))
}

// TotalPostsEQ applies the EQ predicate on the "total_posts" field.
func TotalPostsEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldEQ(FieldTotalPosts, v))
}

// TotalPostsNEQ applies the NEQ predicate on the "total_posts" field.
func TotalPostsNEQ(v int) predicate.Channel {
	return predicate.Channel(sql.FieldNEQ(FieldTotalPosts, v))
}

// TotalPostsIn applies the In predicate on the "total_posts" field.
func TotalPostsIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldIn(FieldTotalPosts, vs...))
}

// TotalPostsNotIn applies the NotIn predicate on the "total_posts" field.
func TotalPostsNotIn(vs ...int) predicate.Channel {
	return predicate.Channel(sql.FieldNotIn(FieldTotalPosts, vs...))
}

// TotalPostsGT applies the GT predicate on the "total_posts" field.
func TotalPostsGT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGT(FieldTotalPosts, v))
}

// TotalPostsGTE applies the GTE predicate on the "total_posts" field.
func TotalPostsGTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldGTE(FieldTotalPosts, v))
}

// TotalPostsLT applies the LT predicate on the "total_posts" field.
func TotalPostsLT(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLT(FieldTotalPosts, v))
}

// TotalPostsLTE applies the LTE predicate on the "total_posts" field.
func TotalPostsLTE(v int) predicate.Channel {
	return predicate.Channel(sql.FieldLTE(FieldTotalPosts, v))
}

// TotalPostsIsNil applies the IsNil predicate on the "total_posts" field.
func TotalPostsIsNil() predicate.Channel {
	return predicate.Channel(sql.FieldIsNull(FieldTotalPosts))
}

// TotalPostsNotNil applies the NotNil predicate on the "total_posts" field.
func TotalPostsNotNil() predicate.Channel {
	return predicate.Channel(sql.FieldNotNull(FieldTotalPosts))
}

// HasCustomerChannels applies the HasEdge predicate on the "customer_channels" edge.
func HasCustomerChannels() predicate.Channel {
	return predicate.Channel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CustomerChannelsTable, CustomerChannelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerChannelsWith applies the HasEdge predicate on the "customer_channels" edge with a given conditions (other predicates).
func HasCustomerChannelsWith(preds ...predicate.CustomerChannel) predicate.Channel {
	return predicate.Channel(func(s *sql.Selector) {
		step := newCustomerChannelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeals applies the HasEdge predicate on the "deals" edge.
func HasDeals() predicate.Channel {
	return predicate.Channel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DealsTable, DealsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDealsWith applies the HasEdge predicate on the "deals" edge with a given conditions (other predicates).
func HasDealsWith(preds ...predicate.Deal) predicate.Channel {
	return predicate.Channel(func(s *sql.Selector) {
		step := newDealsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Channel) predicate.Channel {
	return predicate.Channel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Channel) predicate.Channel {
	return predicate.Channel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Channel) predicate.Channel {
	return predicate.Channel(sql.NotPredicates(p))
}
