// Code generated by ent, DO NOT EDIT.

package brief

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the brief type in the database.
	Label = "brief"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCustomerBriefs holds the string denoting the customer_briefs edge name in mutations.
	EdgeCustomerBriefs = "customer_briefs"
	// Table holds the table name of the brief in the database.
	Table = "briefs"
	// CustomerBriefsTable is the table that holds the customer_briefs relation/edge.
	CustomerBriefsTable = "customers_briefs"
	// CustomerBriefsInverseTable is the table name for the CustomerBrief entity.
	// It exists in this package in order to avoid circular dependency with the "customerbrief" package.
	CustomerBriefsInverseTable = "customers_briefs"
	// CustomerBriefsColumn is the table column denoting the customer_briefs relation/edge.
	CustomerBriefsColumn = "brief_id"
)

// Columns holds all SQL columns for brief fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Brief queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCustomerBriefsCount orders the results by customer_briefs count.
func ByCustomerBriefsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCustomerBriefsStep(), opts...)
	}
}

// ByCustomerBriefs orders the results by customer_briefs terms.
func ByCustomerBriefs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomerBriefsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCustomerBriefsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CustomerBriefsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CustomerBriefsTable, CustomerBriefsColumn),
	)
}
