// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/wickedv43/TAM-backend/internal/database/ent/botstate"
	"github.com/wickedv43/TAM-backend/internal/database/ent/brief"
	"github.com/wickedv43/TAM-backend/internal/database/ent/channel"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customer"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customerbrief"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customerchannel"
	"github.com/wickedv43/TAM-backend/internal/database/ent/deal"
	"github.com/wickedv43/TAM-backend/internal/database/ent/indexerstate"
	"github.com/wickedv43/TAM-backend/internal/database/ent/transaction"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BotState is the client for interacting with the BotState builders.
	BotState *BotStateClient
	// Brief is the client for interacting with the Brief builders.
	Brief *BriefClient
	// Channel is the client for interacting with the Channel builders.
	Channel *ChannelClient
	// Customer is the client for interacting with the Customer builders.
	Customer *CustomerClient
	// CustomerBrief is the client for interacting with the CustomerBrief builders.
	CustomerBrief *CustomerBriefClient
	// CustomerChannel is the client for interacting with the CustomerChannel builders.
	CustomerChannel *CustomerChannelClient
	// Deal is the client for interacting with the Deal builders.
	Deal *DealClient
	// IndexerState is the client for interacting with the IndexerState builders.
	IndexerState *IndexerStateClient
	// Transaction is the client for interacting with the Transaction builders.
	Transaction *TransactionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BotState = NewBotStateClient(c.config)
	c.Brief = NewBriefClient(c.config)
	c.Channel = NewChannelClient(c.config)
	c.Customer = NewCustomerClient(c.config)
	c.CustomerBrief = NewCustomerBriefClient(c.config)
	c.CustomerChannel = NewCustomerChannelClient(c.config)
	c.Deal = NewDealClient(c.config)
	c.IndexerState = NewIndexerStateClient(c.config)
	c.Transaction = NewTransactionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		BotState:        NewBotStateClient(cfg),
		Brief:           NewBriefClient(cfg),
		Channel:         NewChannelClient(cfg),
		Customer:        NewCustomerClient(cfg),
		CustomerBrief:   NewCustomerBriefClient(cfg),
		CustomerChannel: NewCustomerChannelClient(cfg),
		Deal:            NewDealClient(cfg),
		IndexerState:    NewIndexerStateClient(cfg),
		Transaction:     NewTransactionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		BotState:        NewBotStateClient(cfg),
		Brief:           NewBriefClient(cfg),
		Channel:         NewChannelClient(cfg),
		Customer:        NewCustomerClient(cfg),
		CustomerBrief:   NewCustomerBriefClient(cfg),
		CustomerChannel: NewCustomerChannelClient(cfg),
		Deal:            NewDealClient(cfg),
		IndexerState:    NewIndexerStateClient(cfg),
		Transaction:     NewTransactionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BotState.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.BotState, c.Brief, c.Channel, c.Customer, c.CustomerBrief, c.CustomerChannel,
		c.Deal, c.IndexerState, c.Transaction,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.BotState, c.Brief, c.Channel, c.Customer, c.CustomerBrief, c.CustomerChannel,
		c.Deal, c.IndexerState, c.Transaction,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BotStateMutation:
		return c.BotState.mutate(ctx, m)
	case *BriefMutation:
		return c.Brief.mutate(ctx, m)
	case *ChannelMutation:
		return c.Channel.mutate(ctx, m)
	case *CustomerMutation:
		return c.Customer.mutate(ctx, m)
	case *CustomerBriefMutation:
		return c.CustomerBrief.mutate(ctx, m)
	case *CustomerChannelMutation:
		return c.CustomerChannel.mutate(ctx, m)
	case *DealMutation:
		return c.Deal.mutate(ctx, m)
	case *IndexerStateMutation:
		return c.IndexerState.mutate(ctx, m)
	case *TransactionMutation:
		return c.Transaction.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BotStateClient is a client for the BotState schema.
type BotStateClient struct {
	config
}

// NewBotStateClient returns a client for the BotState from the given config.
func NewBotStateClient(c config) *BotStateClient {
	return &BotStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `botstate.Hooks(f(g(h())))`.
func (c *BotStateClient) Use(hooks ...Hook) {
	c.hooks.BotState = append(c.hooks.BotState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `botstate.Intercept(f(g(h())))`.
func (c *BotStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.BotState = append(c.inters.BotState, interceptors...)
}

// Create returns a builder for creating a BotState entity.
func (c *BotStateClient) Create() *BotStateCreate {
	mutation := newBotStateMutation(c.config, OpCreate)
	return &BotStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BotState entities.
func (c *BotStateClient) CreateBulk(builders ...*BotStateCreate) *BotStateCreateBulk {
	return &BotStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BotStateClient) MapCreateBulk(slice any, setFunc func(*BotStateCreate, int)) *BotStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BotStateCreateBulk{err: fmt.Errorf("calling to BotStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BotStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BotStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BotState.
func (c *BotStateClient) Update() *BotStateUpdate {
	mutation := newBotStateMutation(c.config, OpUpdate)
	return &BotStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BotStateClient) UpdateOne(_m *BotState) *BotStateUpdateOne {
	mutation := newBotStateMutation(c.config, OpUpdateOne, withBotState(_m))
	return &BotStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BotStateClient) UpdateOneID(id int) *BotStateUpdateOne {
	mutation := newBotStateMutation(c.config, OpUpdateOne, withBotStateID(id))
	return &BotStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BotState.
func (c *BotStateClient) Delete() *BotStateDelete {
	mutation := newBotStateMutation(c.config, OpDelete)
	return &BotStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BotStateClient) DeleteOne(_m *BotState) *BotStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BotStateClient) DeleteOneID(id int) *BotStateDeleteOne {
	builder := c.Delete().Where(botstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BotStateDeleteOne{builder}
}

// Query returns a query builder for BotState.
func (c *BotStateClient) Query() *BotStateQuery {
	return &BotStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBotState},
		inters: c.Interceptors(),
	}
}

// Get returns a BotState entity by its id.
func (c *BotStateClient) Get(ctx context.Context, id int) (*BotState, error) {
	return c.Query().Where(botstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BotStateClient) GetX(ctx context.Context, id int) *BotState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BotStateClient) Hooks() []Hook {
	return c.hooks.BotState
}

// Interceptors returns the client interceptors.
func (c *BotStateClient) Interceptors() []Interceptor {
	return c.inters.BotState
}

func (c *BotStateClient) mutate(ctx context.Context, m *BotStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BotStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BotStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BotStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BotStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BotState mutation op: %q", m.Op())
	}
}

// BriefClient is a client for the Brief schema.
type BriefClient struct {
	config
}

// NewBriefClient returns a client for the Brief from the given config.
func NewBriefClient(c config) *BriefClient {
	return &BriefClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `brief.Hooks(f(g(h())))`.
func (c *BriefClient) Use(hooks ...Hook) {
	c.hooks.Brief = append(c.hooks.Brief, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `brief.Intercept(f(g(h())))`.
func (c *BriefClient) Intercept(interceptors ...Interceptor) {
	c.inters.Brief = append(c.inters.Brief, interceptors...)
}

// Create returns a builder for creating a Brief entity.
func (c *BriefClient) Create() *BriefCreate {
	mutation := newBriefMutation(c.config, OpCreate)
	return &BriefCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Brief entities.
func (c *BriefClient) CreateBulk(builders ...*BriefCreate) *BriefCreateBulk {
	return &BriefCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BriefClient) MapCreateBulk(slice any, setFunc func(*BriefCreate, int)) *BriefCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BriefCreateBulk{err: fmt.Errorf("calling to BriefClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BriefCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BriefCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Brief.
func (c *BriefClient) Update() *BriefUpdate {
	mutation := newBriefMutation(c.config, OpUpdate)
	return &BriefUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BriefClient) UpdateOne(_m *Brief) *BriefUpdateOne {
	mutation := newBriefMutation(c.config, OpUpdateOne, withBrief(_m))
	return &BriefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BriefClient) UpdateOneID(id uuid.UUID) *BriefUpdateOne {
	mutation := newBriefMutation(c.config, OpUpdateOne, withBriefID(id))
	return &BriefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Brief.
func (c *BriefClient) Delete() *BriefDelete {
	mutation := newBriefMutation(c.config, OpDelete)
	return &BriefDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BriefClient) DeleteOne(_m *Brief) *BriefDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BriefClient) DeleteOneID(id uuid.UUID) *BriefDeleteOne {
	builder := c.Delete().Where(brief.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BriefDeleteOne{builder}
}

// Query returns a query builder for Brief.
func (c *BriefClient) Query() *BriefQuery {
	return &BriefQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBrief},
		inters: c.Interceptors(),
	}
}

// Get returns a Brief entity by its id.
func (c *BriefClient) Get(ctx context.Context, id uuid.UUID) (*Brief, error) {
	return c.Query().Where(brief.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BriefClient) GetX(ctx context.Context, id uuid.UUID) *Brief {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCustomerBriefs queries the customer_briefs edge of a Brief.
func (c *BriefClient) QueryCustomerBriefs(_m *Brief) *CustomerBriefQuery {
	query := (&CustomerBriefClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(brief.Table, brief.FieldID, id),
			sqlgraph.To(customerbrief.Table, customerbrief.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, brief.CustomerBriefsTable, brief.CustomerBriefsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BriefClient) Hooks() []Hook {
	return c.hooks.Brief
}

// Interceptors returns the client interceptors.
func (c *BriefClient) Interceptors() []Interceptor {
	return c.inters.Brief
}

func (c *BriefClient) mutate(ctx context.Context, m *BriefMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BriefCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BriefUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BriefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BriefDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Brief mutation op: %q", m.Op())
	}
}

// ChannelClient is a client for the Channel schema.
type ChannelClient struct {
	config
}

// NewChannelClient returns a client for the Channel from the given config.
func NewChannelClient(c config) *ChannelClient {
	return &ChannelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channel.Hooks(f(g(h())))`.
func (c *ChannelClient) Use(hooks ...Hook) {
	c.hooks.Channel = append(c.hooks.Channel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channel.Intercept(f(g(h())))`.
func (c *ChannelClient) Intercept(interceptors ...Interceptor) {
	c.inters.Channel = append(c.inters.Channel, interceptors...)
}

// Create returns a builder for creating a Channel entity.
func (c *ChannelClient) Create() *ChannelCreate {
	mutation := newChannelMutation(c.config, OpCreate)
	return &ChannelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Channel entities.
func (c *ChannelClient) CreateBulk(builders ...*ChannelCreate) *ChannelCreateBulk {
	return &ChannelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelClient) MapCreateBulk(slice any, setFunc func(*ChannelCreate, int)) *ChannelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelCreateBulk{err: fmt.Errorf("calling to ChannelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Channel.
func (c *ChannelClient) Update() *ChannelUpdate {
	mutation := newChannelMutation(c.config, OpUpdate)
	return &ChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelClient) UpdateOne(_m *Channel) *ChannelUpdateOne {
	mutation := newChannelMutation(c.config, OpUpdateOne, withChannel(_m))
	return &ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelClient) UpdateOneID(id uuid.UUID) *ChannelUpdateOne {
	mutation := newChannelMutation(c.config, OpUpdateOne, withChannelID(id))
	return &ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Channel.
func (c *ChannelClient) Delete() *ChannelDelete {
	mutation := newChannelMutation(c.config, OpDelete)
	return &ChannelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelClient) DeleteOne(_m *Channel) *ChannelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelClient) DeleteOneID(id uuid.UUID) *ChannelDeleteOne {
	builder := c.Delete().Where(channel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelDeleteOne{builder}
}

// Query returns a query builder for Channel.
func (c *ChannelClient) Query() *ChannelQuery {
	return &ChannelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannel},
		inters: c.Interceptors(),
	}
}

// Get returns a Channel entity by its id.
func (c *ChannelClient) Get(ctx context.Context, id uuid.UUID) (*Channel, error) {
	return c.Query().Where(channel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelClient) GetX(ctx context.Context, id uuid.UUID) *Channel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCustomerChannels queries the customer_channels edge of a Channel.
func (c *ChannelClient) QueryCustomerChannels(_m *Channel) *CustomerChannelQuery {
	query := (&CustomerChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(customerchannel.Table, customerchannel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.CustomerChannelsTable, channel.CustomerChannelsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDeals queries the deals edge of a Channel.
func (c *ChannelClient) QueryDeals(_m *Channel) *DealQuery {
	query := (&DealClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, id),
			sqlgraph.To(deal.Table, deal.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.DealsTable, channel.DealsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChannelClient) Hooks() []Hook {
	return c.hooks.Channel
}

// Interceptors returns the client interceptors.
func (c *ChannelClient) Interceptors() []Interceptor {
	return c.inters.Channel
}

func (c *ChannelClient) mutate(ctx context.Context, m *ChannelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Channel mutation op: %q", m.Op())
	}
}

// CustomerClient is a client for the Customer schema.
type CustomerClient struct {
	config
}

// NewCustomerClient returns a client for the Customer from the given config.
func NewCustomerClient(c config) *CustomerClient {
	return &CustomerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customer.Hooks(f(g(h())))`.
func (c *CustomerClient) Use(hooks ...Hook) {
	c.hooks.Customer = append(c.hooks.Customer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `customer.Intercept(f(g(h())))`.
func (c *CustomerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Customer = append(c.inters.Customer, interceptors...)
}

// Create returns a builder for creating a Customer entity.
func (c *CustomerClient) Create() *CustomerCreate {
	mutation := newCustomerMutation(c.config, OpCreate)
	return &CustomerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Customer entities.
func (c *CustomerClient) CreateBulk(builders ...*CustomerCreate) *CustomerCreateBulk {
	return &CustomerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomerClient) MapCreateBulk(slice any, setFunc func(*CustomerCreate, int)) *CustomerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomerCreateBulk{err: fmt.Errorf("calling to CustomerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Customer.
func (c *CustomerClient) Update() *CustomerUpdate {
	mutation := newCustomerMutation(c.config, OpUpdate)
	return &CustomerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomerClient) UpdateOne(_m *Customer) *CustomerUpdateOne {
	mutation := newCustomerMutation(c.config, OpUpdateOne, withCustomer(_m))
	return &CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomerClient) UpdateOneID(id uuid.UUID) *CustomerUpdateOne {
	mutation := newCustomerMutation(c.config, OpUpdateOne, withCustomerID(id))
	return &CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Customer.
func (c *CustomerClient) Delete() *CustomerDelete {
	mutation := newCustomerMutation(c.config, OpDelete)
	return &CustomerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomerClient) DeleteOne(_m *Customer) *CustomerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomerClient) DeleteOneID(id uuid.UUID) *CustomerDeleteOne {
	builder := c.Delete().Where(customer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomerDeleteOne{builder}
}

// Query returns a query builder for Customer.
func (c *CustomerClient) Query() *CustomerQuery {
	return &CustomerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomer},
		inters: c.Interceptors(),
	}
}

// Get returns a Customer entity by its id.
func (c *CustomerClient) Get(ctx context.Context, id uuid.UUID) (*Customer, error) {
	return c.Query().Where(customer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomerClient) GetX(ctx context.Context, id uuid.UUID) *Customer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCustomerChannels queries the customer_channels edge of a Customer.
func (c *CustomerClient) QueryCustomerChannels(_m *Customer) *CustomerChannelQuery {
	query := (&CustomerChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customer.Table, customer.FieldID, id),
			sqlgraph.To(customerchannel.Table, customerchannel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, customer.CustomerChannelsTable, customer.CustomerChannelsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCustomerBriefs queries the customer_briefs edge of a Customer.
func (c *CustomerClient) QueryCustomerBriefs(_m *Customer) *CustomerBriefQuery {
	query := (&CustomerBriefClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customer.Table, customer.FieldID, id),
			sqlgraph.To(customerbrief.Table, customerbrief.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, customer.CustomerBriefsTable, customer.CustomerBriefsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAdvertiserDeals queries the advertiser_deals edge of a Customer.
func (c *CustomerClient) QueryAdvertiserDeals(_m *Customer) *DealQuery {
	query := (&DealClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customer.Table, customer.FieldID, id),
			sqlgraph.To(deal.Table, deal.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, customer.AdvertiserDealsTable, customer.AdvertiserDealsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryManagedDeals queries the managed_deals edge of a Customer.
func (c *CustomerClient) QueryManagedDeals(_m *Customer) *DealQuery {
	query := (&DealClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customer.Table, customer.FieldID, id),
			sqlgraph.To(deal.Table, deal.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, customer.ManagedDealsTable, customer.ManagedDealsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CustomerClient) Hooks() []Hook {
	return c.hooks.Customer
}

// Interceptors returns the client interceptors.
func (c *CustomerClient) Interceptors() []Interceptor {
	return c.inters.Customer
}

func (c *CustomerClient) mutate(ctx context.Context, m *CustomerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Customer mutation op: %q", m.Op())
	}
}

// CustomerBriefClient is a client for the CustomerBrief schema.
type CustomerBriefClient struct {
	config
}

// NewCustomerBriefClient returns a client for the CustomerBrief from the given config.
func NewCustomerBriefClient(c config) *CustomerBriefClient {
	return &CustomerBriefClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customerbrief.Hooks(f(g(h())))`.
func (c *CustomerBriefClient) Use(hooks ...Hook) {
	c.hooks.CustomerBrief = append(c.hooks.CustomerBrief, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `customerbrief.Intercept(f(g(h())))`.
func (c *CustomerBriefClient) Intercept(interceptors ...Interceptor) {
	c.inters.CustomerBrief = append(c.inters.CustomerBrief, interceptors...)
}

// Create returns a builder for creating a CustomerBrief entity.
func (c *CustomerBriefClient) Create() *CustomerBriefCreate {
	mutation := newCustomerBriefMutation(c.config, OpCreate)
	return &CustomerBriefCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CustomerBrief entities.
func (c *CustomerBriefClient) CreateBulk(builders ...*CustomerBriefCreate) *CustomerBriefCreateBulk {
	return &CustomerBriefCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomerBriefClient) MapCreateBulk(slice any, setFunc func(*CustomerBriefCreate, int)) *CustomerBriefCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomerBriefCreateBulk{err: fmt.Errorf("calling to CustomerBriefClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomerBriefCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomerBriefCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CustomerBrief.
func (c *CustomerBriefClient) Update() *CustomerBriefUpdate {
	mutation := newCustomerBriefMutation(c.config, OpUpdate)
	return &CustomerBriefUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomerBriefClient) UpdateOne(_m *CustomerBrief) *CustomerBriefUpdateOne {
	mutation := newCustomerBriefMutation(c.config, OpUpdateOne, withCustomerBrief(_m))
	return &CustomerBriefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomerBriefClient) UpdateOneID(id uuid.UUID) *CustomerBriefUpdateOne {
	mutation := newCustomerBriefMutation(c.config, OpUpdateOne, withCustomerBriefID(id))
	return &CustomerBriefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CustomerBrief.
func (c *CustomerBriefClient) Delete() *CustomerBriefDelete {
	mutation := newCustomerBriefMutation(c.config, OpDelete)
	return &CustomerBriefDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomerBriefClient) DeleteOne(_m *CustomerBrief) *CustomerBriefDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomerBriefClient) DeleteOneID(id uuid.UUID) *CustomerBriefDeleteOne {
	builder := c.Delete().Where(customerbrief.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomerBriefDeleteOne{builder}
}

// Query returns a query builder for CustomerBrief.
func (c *CustomerBriefClient) Query() *CustomerBriefQuery {
	return &CustomerBriefQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomerBrief},
		inters: c.Interceptors(),
	}
}

// Get returns a CustomerBrief entity by its id.
func (c *CustomerBriefClient) Get(ctx context.Context, id uuid.UUID) (*CustomerBrief, error) {
	return c.Query().Where(customerbrief.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomerBriefClient) GetX(ctx context.Context, id uuid.UUID) *CustomerBrief {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCustomer queries the customer edge of a CustomerBrief.
func (c *CustomerBriefClient) QueryCustomer(_m *CustomerBrief) *CustomerQuery {
	query := (&CustomerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customerbrief.Table, customerbrief.FieldID, id),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, customerbrief.CustomerTable, customerbrief.CustomerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBrief queries the brief edge of a CustomerBrief.
func (c *CustomerBriefClient) QueryBrief(_m *CustomerBrief) *BriefQuery {
	query := (&BriefClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customerbrief.Table, customerbrief.FieldID, id),
			sqlgraph.To(brief.Table, brief.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, customerbrief.BriefTable, customerbrief.BriefColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CustomerBriefClient) Hooks() []Hook {
	return c.hooks.CustomerBrief
}

// Interceptors returns the client interceptors.
func (c *CustomerBriefClient) Interceptors() []Interceptor {
	return c.inters.CustomerBrief
}

func (c *CustomerBriefClient) mutate(ctx context.Context, m *CustomerBriefMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomerBriefCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomerBriefUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomerBriefUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomerBriefDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CustomerBrief mutation op: %q", m.Op())
	}
}

// CustomerChannelClient is a client for the CustomerChannel schema.
type CustomerChannelClient struct {
	config
}

// NewCustomerChannelClient returns a client for the CustomerChannel from the given config.
func NewCustomerChannelClient(c config) *CustomerChannelClient {
	return &CustomerChannelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customerchannel.Hooks(f(g(h())))`.
func (c *CustomerChannelClient) Use(hooks ...Hook) {
	c.hooks.CustomerChannel = append(c.hooks.CustomerChannel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `customerchannel.Intercept(f(g(h())))`.
func (c *CustomerChannelClient) Intercept(interceptors ...Interceptor) {
	c.inters.CustomerChannel = append(c.inters.CustomerChannel, interceptors...)
}

// Create returns a builder for creating a CustomerChannel entity.
func (c *CustomerChannelClient) Create() *CustomerChannelCreate {
	mutation := newCustomerChannelMutation(c.config, OpCreate)
	return &CustomerChannelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CustomerChannel entities.
func (c *CustomerChannelClient) CreateBulk(builders ...*CustomerChannelCreate) *CustomerChannelCreateBulk {
	return &CustomerChannelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomerChannelClient) MapCreateBulk(slice any, setFunc func(*CustomerChannelCreate, int)) *CustomerChannelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomerChannelCreateBulk{err: fmt.Errorf("calling to CustomerChannelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomerChannelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomerChannelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CustomerChannel.
func (c *CustomerChannelClient) Update() *CustomerChannelUpdate {
	mutation := newCustomerChannelMutation(c.config, OpUpdate)
	return &CustomerChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomerChannelClient) UpdateOne(_m *CustomerChannel) *CustomerChannelUpdateOne {
	mutation := newCustomerChannelMutation(c.config, OpUpdateOne, withCustomerChannel(_m))
	return &CustomerChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomerChannelClient) UpdateOneID(id uuid.UUID) *CustomerChannelUpdateOne {
	mutation := newCustomerChannelMutation(c.config, OpUpdateOne, withCustomerChannelID(id))
	return &CustomerChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CustomerChannel.
func (c *CustomerChannelClient) Delete() *CustomerChannelDelete {
	mutation := newCustomerChannelMutation(c.config, OpDelete)
	return &CustomerChannelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomerChannelClient) DeleteOne(_m *CustomerChannel) *CustomerChannelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomerChannelClient) DeleteOneID(id uuid.UUID) *CustomerChannelDeleteOne {
	builder := c.Delete().Where(customerchannel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomerChannelDeleteOne{builder}
}

// Query returns a query builder for CustomerChannel.
func (c *CustomerChannelClient) Query() *CustomerChannelQuery {
	return &CustomerChannelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomerChannel},
		inters: c.Interceptors(),
	}
}

// Get returns a CustomerChannel entity by its id.
func (c *CustomerChannelClient) Get(ctx context.Context, id uuid.UUID) (*CustomerChannel, error) {
	return c.Query().Where(customerchannel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomerChannelClient) GetX(ctx context.Context, id uuid.UUID) *CustomerChannel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCustomer queries the customer edge of a CustomerChannel.
func (c *CustomerChannelClient) QueryCustomer(_m *CustomerChannel) *CustomerQuery {
	query := (&CustomerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customerchannel.Table, customerchannel.FieldID, id),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, customerchannel.CustomerTable, customerchannel.CustomerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannel queries the channel edge of a CustomerChannel.
func (c *CustomerChannelClient) QueryChannel(_m *CustomerChannel) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customerchannel.Table, customerchannel.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, customerchannel.ChannelTable, customerchannel.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CustomerChannelClient) Hooks() []Hook {
	return c.hooks.CustomerChannel
}

// Interceptors returns the client interceptors.
func (c *CustomerChannelClient) Interceptors() []Interceptor {
	return c.inters.CustomerChannel
}

func (c *CustomerChannelClient) mutate(ctx context.Context, m *CustomerChannelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomerChannelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomerChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomerChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomerChannelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CustomerChannel mutation op: %q", m.Op())
	}
}

// DealClient is a client for the Deal schema.
type DealClient struct {
	config
}

// NewDealClient returns a client for the Deal from the given config.
func NewDealClient(c config) *DealClient {
	return &DealClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `deal.Hooks(f(g(h())))`.
func (c *DealClient) Use(hooks ...Hook) {
	c.hooks.Deal = append(c.hooks.Deal, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `deal.Intercept(f(g(h())))`.
func (c *DealClient) Intercept(interceptors ...Interceptor) {
	c.inters.Deal = append(c.inters.Deal, interceptors...)
}

// Create returns a builder for creating a Deal entity.
func (c *DealClient) Create() *DealCreate {
	mutation := newDealMutation(c.config, OpCreate)
	return &DealCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Deal entities.
func (c *DealClient) CreateBulk(builders ...*DealCreate) *DealCreateBulk {
	return &DealCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DealClient) MapCreateBulk(slice any, setFunc func(*DealCreate, int)) *DealCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DealCreateBulk{err: fmt.Errorf("calling to DealClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DealCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DealCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Deal.
func (c *DealClient) Update() *DealUpdate {
	mutation := newDealMutation(c.config, OpUpdate)
	return &DealUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DealClient) UpdateOne(_m *Deal) *DealUpdateOne {
	mutation := newDealMutation(c.config, OpUpdateOne, withDeal(_m))
	return &DealUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DealClient) UpdateOneID(id uuid.UUID) *DealUpdateOne {
	mutation := newDealMutation(c.config, OpUpdateOne, withDealID(id))
	return &DealUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Deal.
func (c *DealClient) Delete() *DealDelete {
	mutation := newDealMutation(c.config, OpDelete)
	return &DealDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DealClient) DeleteOne(_m *Deal) *DealDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DealClient) DeleteOneID(id uuid.UUID) *DealDeleteOne {
	builder := c.Delete().Where(deal.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DealDeleteOne{builder}
}

// Query returns a query builder for Deal.
func (c *DealClient) Query() *DealQuery {
	return &DealQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDeal},
		inters: c.Interceptors(),
	}
}

// Get returns a Deal entity by its id.
func (c *DealClient) Get(ctx context.Context, id uuid.UUID) (*Deal, error) {
	return c.Query().Where(deal.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DealClient) GetX(ctx context.Context, id uuid.UUID) *Deal {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChannel queries the channel edge of a Deal.
func (c *DealClient) QueryChannel(_m *Deal) *ChannelQuery {
	query := (&ChannelClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(deal.Table, deal.FieldID, id),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deal.ChannelTable, deal.ChannelColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAdvertiser queries the advertiser edge of a Deal.
func (c *DealClient) QueryAdvertiser(_m *Deal) *CustomerQuery {
	query := (&CustomerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(deal.Table, deal.FieldID, id),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deal.AdvertiserTable, deal.AdvertiserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChannelManager queries the channel_manager edge of a Deal.
func (c *DealClient) QueryChannelManager(_m *Deal) *CustomerQuery {
	query := (&CustomerClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(deal.Table, deal.FieldID, id),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deal.ChannelManagerTable, deal.ChannelManagerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DealClient) Hooks() []Hook {
	return c.hooks.Deal
}

// Interceptors returns the client interceptors.
func (c *DealClient) Interceptors() []Interceptor {
	return c.inters.Deal
}

func (c *DealClient) mutate(ctx context.Context, m *DealMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DealCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DealUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DealUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DealDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Deal mutation op: %q", m.Op())
	}
}

// IndexerStateClient is a client for the IndexerState schema.
type IndexerStateClient struct {
	config
}

// NewIndexerStateClient returns a client for the IndexerState from the given config.
func NewIndexerStateClient(c config) *IndexerStateClient {
	return &IndexerStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `indexerstate.Hooks(f(g(h())))`.
func (c *IndexerStateClient) Use(hooks ...Hook) {
	c.hooks.IndexerState = append(c.hooks.IndexerState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `indexerstate.Intercept(f(g(h())))`.
func (c *IndexerStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.IndexerState = append(c.inters.IndexerState, interceptors...)
}

// Create returns a builder for creating a IndexerState entity.
func (c *IndexerStateClient) Create() *IndexerStateCreate {
	mutation := newIndexerStateMutation(c.config, OpCreate)
	return &IndexerStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of IndexerState entities.
func (c *IndexerStateClient) CreateBulk(builders ...*IndexerStateCreate) *IndexerStateCreateBulk {
	return &IndexerStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *IndexerStateClient) MapCreateBulk(slice any, setFunc func(*IndexerStateCreate, int)) *IndexerStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &IndexerStateCreateBulk{err: fmt.Errorf("calling to IndexerStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*IndexerStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &IndexerStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for IndexerState.
func (c *IndexerStateClient) Update() *IndexerStateUpdate {
	mutation := newIndexerStateMutation(c.config, OpUpdate)
	return &IndexerStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IndexerStateClient) UpdateOne(_m *IndexerState) *IndexerStateUpdateOne {
	mutation := newIndexerStateMutation(c.config, OpUpdateOne, withIndexerState(_m))
	return &IndexerStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IndexerStateClient) UpdateOneID(id uuid.UUID) *IndexerStateUpdateOne {
	mutation := newIndexerStateMutation(c.config, OpUpdateOne, withIndexerStateID(id))
	return &IndexerStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for IndexerState.
func (c *IndexerStateClient) Delete() *IndexerStateDelete {
	mutation := newIndexerStateMutation(c.config, OpDelete)
	return &IndexerStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *IndexerStateClient) DeleteOne(_m *IndexerState) *IndexerStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *IndexerStateClient) DeleteOneID(id uuid.UUID) *IndexerStateDeleteOne {
	builder := c.Delete().Where(indexerstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IndexerStateDeleteOne{builder}
}

// Query returns a query builder for IndexerState.
func (c *IndexerStateClient) Query() *IndexerStateQuery {
	return &IndexerStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeIndexerState},
		inters: c.Interceptors(),
	}
}

// Get returns a IndexerState entity by its id.
func (c *IndexerStateClient) Get(ctx context.Context, id uuid.UUID) (*IndexerState, error) {
	return c.Query().Where(indexerstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IndexerStateClient) GetX(ctx context.Context, id uuid.UUID) *IndexerState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *IndexerStateClient) Hooks() []Hook {
	return c.hooks.IndexerState
}

// Interceptors returns the client interceptors.
func (c *IndexerStateClient) Interceptors() []Interceptor {
	return c.inters.IndexerState
}

func (c *IndexerStateClient) mutate(ctx context.Context, m *IndexerStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&IndexerStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&IndexerStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&IndexerStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&IndexerStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown IndexerState mutation op: %q", m.Op())
	}
}

// TransactionClient is a client for the Transaction schema.
type TransactionClient struct {
	config
}

// NewTransactionClient returns a client for the Transaction from the given config.
func NewTransactionClient(c config) *TransactionClient {
	return &TransactionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `transaction.Hooks(f(g(h())))`.
func (c *TransactionClient) Use(hooks ...Hook) {
	c.hooks.Transaction = append(c.hooks.Transaction, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `transaction.Intercept(f(g(h())))`.
func (c *TransactionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Transaction = append(c.inters.Transaction, interceptors...)
}

// Create returns a builder for creating a Transaction entity.
func (c *TransactionClient) Create() *TransactionCreate {
	mutation := newTransactionMutation(c.config, OpCreate)
	return &TransactionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Transaction entities.
func (c *TransactionClient) CreateBulk(builders ...*TransactionCreate) *TransactionCreateBulk {
	return &TransactionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TransactionClient) MapCreateBulk(slice any, setFunc func(*TransactionCreate, int)) *TransactionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TransactionCreateBulk{err: fmt.Errorf("calling to TransactionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TransactionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TransactionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Transaction.
func (c *TransactionClient) Update() *TransactionUpdate {
	mutation := newTransactionMutation(c.config, OpUpdate)
	return &TransactionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TransactionClient) UpdateOne(_m *Transaction) *TransactionUpdateOne {
	mutation := newTransactionMutation(c.config, OpUpdateOne, withTransaction(_m))
	return &TransactionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TransactionClient) UpdateOneID(id uuid.UUID) *TransactionUpdateOne {
	mutation := newTransactionMutation(c.config, OpUpdateOne, withTransactionID(id))
	return &TransactionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Transaction.
func (c *TransactionClient) Delete() *TransactionDelete {
	mutation := newTransactionMutation(c.config, OpDelete)
	return &TransactionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TransactionClient) DeleteOne(_m *Transaction) *TransactionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TransactionClient) DeleteOneID(id uuid.UUID) *TransactionDeleteOne {
	builder := c.Delete().Where(transaction.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TransactionDeleteOne{builder}
}

// Query returns a query builder for Transaction.
func (c *TransactionClient) Query() *TransactionQuery {
	return &TransactionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTransaction},
		inters: c.Interceptors(),
	}
}

// Get returns a Transaction entity by its id.
func (c *TransactionClient) Get(ctx context.Context, id uuid.UUID) (*Transaction, error) {
	return c.Query().Where(transaction.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TransactionClient) GetX(ctx context.Context, id uuid.UUID) *Transaction {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TransactionClient) Hooks() []Hook {
	return c.hooks.Transaction
}

// Interceptors returns the client interceptors.
func (c *TransactionClient) Interceptors() []Interceptor {
	return c.inters.Transaction
}

func (c *TransactionClient) mutate(ctx context.Context, m *TransactionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TransactionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TransactionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TransactionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TransactionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Transaction mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BotState, Brief, Channel, Customer, CustomerBrief, CustomerChannel, Deal,
		IndexerState, Transaction []ent.Hook
	}
	inters struct {
		BotState, Brief, Channel, Customer, CustomerBrief, CustomerChannel, Deal,
		IndexerState, Transaction []ent.Interceptor
	}
)
