// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/brief"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customer"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customerbrief"
)

// CustomerBriefCreate is the builder for creating a CustomerBrief entity.
type CustomerBriefCreate struct {
	config
	mutation *CustomerBriefMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomerBriefCreate) SetCreatedAt(v time.Time) *CustomerBriefCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomerBriefCreate) SetNillableCreatedAt(v *time.Time) *CustomerBriefCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomerBriefCreate) SetUpdatedAt(v time.Time) *CustomerBriefCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomerBriefCreate) SetNillableUpdatedAt(v *time.Time) *CustomerBriefCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *CustomerBriefCreate) SetCustomerID(v uuid.UUID) *CustomerBriefCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetBriefID sets the "brief_id" field.
func (_c *CustomerBriefCreate) SetBriefID(v uuid.UUID) *CustomerBriefCreate {
	_c.mutation.SetBriefID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CustomerBriefCreate) SetID(v uuid.UUID) *CustomerBriefCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CustomerBriefCreate) SetNillableID(v *uuid.UUID) *CustomerBriefCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_c *CustomerBriefCreate) SetCustomer(v *Customer) *CustomerBriefCreate {
	return _c.SetCustomerID(v.ID)
}

// SetBrief sets the "brief" edge to the Brief entity.
func (_c *CustomerBriefCreate) SetBrief(v *Brief) *CustomerBriefCreate {
	return _c.SetBriefID(v.ID)
}

// Mutation returns the CustomerBriefMutation object of the builder.
func (_c *CustomerBriefCreate) Mutation() *CustomerBriefMutation {
	return _c.mutation
}

// Save creates the CustomerBrief in the database.
func (_c *CustomerBriefCreate) Save(ctx context.Context) (*CustomerBrief, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomerBriefCreate) SaveX(ctx context.Context) *CustomerBrief {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerBriefCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerBriefCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomerBriefCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := customerbrief.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := customerbrief.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := customerbrief.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomerBriefCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomerBrief.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CustomerBrief.updated_at"`)}
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "CustomerBrief.customer_id"`)}
	}
	if _, ok := _c.mutation.BriefID(); !ok {
		return &ValidationError{Name: "brief_id", err: errors.New(`ent: missing required field "CustomerBrief.brief_id"`)}
	}
	if len(_c.mutation.CustomerIDs()) == 0 {
		return &ValidationError{Name: "customer", err: errors.New(`ent: missing required edge "CustomerBrief.customer"`)}
	}
	if len(_c.mutation.BriefIDs()) == 0 {
		return &ValidationError{Name: "brief", err: errors.New(`ent: missing required edge "CustomerBrief.brief"`)}
	}
	return nil
}

func (_c *CustomerBriefCreate) sqlSave(ctx context.Context) (*CustomerBrief, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomerBriefCreate) createSpec() (*CustomerBrief, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomerBrief{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customerbrief.Table, sqlgraph.NewFieldSpec(customerbrief.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(customerbrief.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(customerbrief.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerbrief.CustomerTable,
			Columns: []string{customerbrief.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BriefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerbrief.BriefTable,
			Columns: []string{customerbrief.BriefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(brief.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BriefID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomerBrief.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerBriefUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomerBriefCreate) OnConflict(opts ...sql.ConflictOption) *CustomerBriefUpsertOne {
	_c.conflict = opts
	return &CustomerBriefUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomerBrief.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomerBriefCreate) OnConflictColumns(columns ...string) *CustomerBriefUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomerBriefUpsertOne{
		create: _c,
	}
}

type (
	// CustomerBriefUpsertOne is the builder for "upsert"-ing
	//  one CustomerBrief node.
	CustomerBriefUpsertOne struct {
		create *CustomerBriefCreate
	}

	// CustomerBriefUpsert is the "OnConflict" setter.
	CustomerBriefUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerBriefUpsert) SetUpdatedAt(v time.Time) *CustomerBriefUpsert {
	u.Set(customerbrief.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerBriefUpsert) UpdateUpdatedAt() *CustomerBriefUpsert {
	u.SetExcluded(customerbrief.FieldUpdatedAt)
	return u
}

// SetCustomerID sets the "customer_id" field.
func (u *CustomerBriefUpsert) SetCustomerID(v uuid.UUID) *CustomerBriefUpsert {
	u.Set(customerbrief.FieldCustomerID, v)
	return u
}

// UpdateCustomerID sets the "customer_id" field to the value that was provided on create.
func (u *CustomerBriefUpsert) UpdateCustomerID() *CustomerBriefUpsert {
	u.SetExcluded(customerbrief.FieldCustomerID)
	return u
}

// SetBriefID sets the "brief_id" field.
func (u *CustomerBriefUpsert) SetBriefID(v uuid.UUID) *CustomerBriefUpsert {
	u.Set(customerbrief.FieldBriefID, v)
	return u
}

// UpdateBriefID sets the "brief_id" field to the value that was provided on create.
func (u *CustomerBriefUpsert) UpdateBriefID() *CustomerBriefUpsert {
	u.SetExcluded(customerbrief.FieldBriefID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CustomerBrief.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customerbrief.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerBriefUpsertOne) UpdateNewValues() *CustomerBriefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(customerbrief.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(customerbrief.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomerBrief.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomerBriefUpsertOne) Ignore() *CustomerBriefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerBriefUpsertOne) DoNothing() *CustomerBriefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerBriefCreate.OnConflict
// documentation for more info.
func (u *CustomerBriefUpsertOne) Update(set func(*CustomerBriefUpsert)) *CustomerBriefUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerBriefUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerBriefUpsertOne) SetUpdatedAt(v time.Time) *CustomerBriefUpsertOne {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerBriefUpsertOne) UpdateUpdatedAt() *CustomerBriefUpsertOne {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCustomerID sets the "customer_id" field.
func (u *CustomerBriefUpsertOne) SetCustomerID(v uuid.UUID) *CustomerBriefUpsertOne {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.SetCustomerID(v)
	})
}

// UpdateCustomerID sets the "customer_id" field to the value that was provided on create.
func (u *CustomerBriefUpsertOne) UpdateCustomerID() *CustomerBriefUpsertOne {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.UpdateCustomerID()
	})
}

// SetBriefID sets the "brief_id" field.
func (u *CustomerBriefUpsertOne) SetBriefID(v uuid.UUID) *CustomerBriefUpsertOne {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.SetBriefID(v)
	})
}

// UpdateBriefID sets the "brief_id" field to the value that was provided on create.
func (u *CustomerBriefUpsertOne) UpdateBriefID() *CustomerBriefUpsertOne {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.UpdateBriefID()
	})
}

// Exec executes the query.
func (u *CustomerBriefUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomerBriefCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerBriefUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomerBriefUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CustomerBriefUpsertOne.ID is not supported by MySQL driver. Use CustomerBriefUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomerBriefUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomerBriefCreateBulk is the builder for creating many CustomerBrief entities in bulk.
type CustomerBriefCreateBulk struct {
	config
	err      error
	builders []*CustomerBriefCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomerBrief entities in the database.
func (_c *CustomerBriefCreateBulk) Save(ctx context.Context) ([]*CustomerBrief, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomerBrief, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerBriefMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomerBriefCreateBulk) SaveX(ctx context.Context) []*CustomerBrief {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerBriefCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerBriefCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomerBrief.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerBriefUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomerBriefCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomerBriefUpsertBulk {
	_c.conflict = opts
	return &CustomerBriefUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomerBrief.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomerBriefCreateBulk) OnConflictColumns(columns ...string) *CustomerBriefUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomerBriefUpsertBulk{
		create: _c,
	}
}

// CustomerBriefUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomerBrief nodes.
type CustomerBriefUpsertBulk struct {
	create *CustomerBriefCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomerBrief.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customerbrief.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerBriefUpsertBulk) UpdateNewValues() *CustomerBriefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(customerbrief.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(customerbrief.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomerBrief.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomerBriefUpsertBulk) Ignore() *CustomerBriefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerBriefUpsertBulk) DoNothing() *CustomerBriefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerBriefCreateBulk.OnConflict
// documentation for more info.
func (u *CustomerBriefUpsertBulk) Update(set func(*CustomerBriefUpsert)) *CustomerBriefUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerBriefUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerBriefUpsertBulk) SetUpdatedAt(v time.Time) *CustomerBriefUpsertBulk {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerBriefUpsertBulk) UpdateUpdatedAt() *CustomerBriefUpsertBulk {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCustomerID sets the "customer_id" field.
func (u *CustomerBriefUpsertBulk) SetCustomerID(v uuid.UUID) *CustomerBriefUpsertBulk {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.SetCustomerID(v)
	})
}

// UpdateCustomerID sets the "customer_id" field to the value that was provided on create.
func (u *CustomerBriefUpsertBulk) UpdateCustomerID() *CustomerBriefUpsertBulk {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.UpdateCustomerID()
	})
}

// SetBriefID sets the "brief_id" field.
func (u *CustomerBriefUpsertBulk) SetBriefID(v uuid.UUID) *CustomerBriefUpsertBulk {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.SetBriefID(v)
	})
}

// UpdateBriefID sets the "brief_id" field to the value that was provided on create.
func (u *CustomerBriefUpsertBulk) UpdateBriefID() *CustomerBriefUpsertBulk {
	return u.Update(func(s *CustomerBriefUpsert) {
		s.UpdateBriefID()
	})
}

// Exec executes the query.
func (u *CustomerBriefUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomerBriefCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomerBriefCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerBriefUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
