// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/channel"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customer"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customerchannel"
	"github.com/wickedv43/TAM-backend/internal/database/ent/predicate"
)

// CustomerChannelUpdate is the builder for updating CustomerChannel entities.
type CustomerChannelUpdate struct {
	config
	hooks    []Hook
	mutation *CustomerChannelMutation
}

// Where appends a list predicates to the CustomerChannelUpdate builder.
func (_u *CustomerChannelUpdate) Where(ps ...predicate.CustomerChannel) *CustomerChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomerChannelUpdate) SetUpdatedAt(v time.Time) *CustomerChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *CustomerChannelUpdate) SetCustomerID(v uuid.UUID) *CustomerChannelUpdate {
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *CustomerChannelUpdate) SetNillableCustomerID(v *uuid.UUID) *CustomerChannelUpdate {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *CustomerChannelUpdate) SetChannelID(v uuid.UUID) *CustomerChannelUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *CustomerChannelUpdate) SetNillableChannelID(v *uuid.UUID) *CustomerChannelUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *CustomerChannelUpdate) SetRole(v int) *CustomerChannelUpdate {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *CustomerChannelUpdate) SetNillableRole(v *int) *CustomerChannelUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds value to the "role" field.
func (_u *CustomerChannelUpdate) AddRole(v int) *CustomerChannelUpdate {
	_u.mutation.AddRole(v)
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *CustomerChannelUpdate) SetPermissions(v []int) *CustomerChannelUpdate {
	_u.mutation.SetPermissions(v)
	return _u
}

// AppendPermissions appends value to the "permissions" field.
func (_u *CustomerChannelUpdate) AppendPermissions(v []int) *CustomerChannelUpdate {
	_u.mutation.AppendPermissions(v)
	return _u
}

// ClearPermissions clears the value of the "permissions" field.
func (_u *CustomerChannelUpdate) ClearPermissions() *CustomerChannelUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_u *CustomerChannelUpdate) SetCustomer(v *Customer) *CustomerChannelUpdate {
	return _u.SetCustomerID(v.ID)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *CustomerChannelUpdate) SetChannel(v *Channel) *CustomerChannelUpdate {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the CustomerChannelMutation object of the builder.
func (_u *CustomerChannelUpdate) Mutation() *CustomerChannelMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (_u *CustomerChannelUpdate) ClearCustomer() *CustomerChannelUpdate {
	_u.mutation.ClearCustomer()
	return _u
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *CustomerChannelUpdate) ClearChannel() *CustomerChannelUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomerChannelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomerChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomerChannelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customerchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomerChannelUpdate) check() error {
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomerChannel.customer"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomerChannel.channel"`)
	}
	return nil
}

func (_u *CustomerChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customerchannel.Table, customerchannel.Columns, sqlgraph.NewFieldSpec(customerchannel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customerchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(customerchannel.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(customerchannel.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(customerchannel.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, customerchannel.FieldPermissions, value)
		})
	}
	if _u.mutation.PermissionsCleared() {
		_spec.ClearField(customerchannel.FieldPermissions, field.TypeJSON)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerchannel.CustomerTable,
			Columns: []string{customerchannel.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerchannel.CustomerTable,
			Columns: []string{customerchannel.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerchannel.ChannelTable,
			Columns: []string{customerchannel.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerchannel.ChannelTable,
			Columns: []string{customerchannel.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customerchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomerChannelUpdateOne is the builder for updating a single CustomerChannel entity.
type CustomerChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomerChannelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomerChannelUpdateOne) SetUpdatedAt(v time.Time) *CustomerChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *CustomerChannelUpdateOne) SetCustomerID(v uuid.UUID) *CustomerChannelUpdateOne {
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *CustomerChannelUpdateOne) SetNillableCustomerID(v *uuid.UUID) *CustomerChannelUpdateOne {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *CustomerChannelUpdateOne) SetChannelID(v uuid.UUID) *CustomerChannelUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *CustomerChannelUpdateOne) SetNillableChannelID(v *uuid.UUID) *CustomerChannelUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *CustomerChannelUpdateOne) SetRole(v int) *CustomerChannelUpdateOne {
	_u.mutation.ResetRole()
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *CustomerChannelUpdateOne) SetNillableRole(v *int) *CustomerChannelUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// AddRole adds value to the "role" field.
func (_u *CustomerChannelUpdateOne) AddRole(v int) *CustomerChannelUpdateOne {
	_u.mutation.AddRole(v)
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *CustomerChannelUpdateOne) SetPermissions(v []int) *CustomerChannelUpdateOne {
	_u.mutation.SetPermissions(v)
	return _u
}

// AppendPermissions appends value to the "permissions" field.
func (_u *CustomerChannelUpdateOne) AppendPermissions(v []int) *CustomerChannelUpdateOne {
	_u.mutation.AppendPermissions(v)
	return _u
}

// ClearPermissions clears the value of the "permissions" field.
func (_u *CustomerChannelUpdateOne) ClearPermissions() *CustomerChannelUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_u *CustomerChannelUpdateOne) SetCustomer(v *Customer) *CustomerChannelUpdateOne {
	return _u.SetCustomerID(v.ID)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *CustomerChannelUpdateOne) SetChannel(v *Channel) *CustomerChannelUpdateOne {
	return _u.SetChannelID(v.ID)
}

// Mutation returns the CustomerChannelMutation object of the builder.
func (_u *CustomerChannelUpdateOne) Mutation() *CustomerChannelMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (_u *CustomerChannelUpdateOne) ClearCustomer() *CustomerChannelUpdateOne {
	_u.mutation.ClearCustomer()
	return _u
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *CustomerChannelUpdateOne) ClearChannel() *CustomerChannelUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// Where appends a list predicates to the CustomerChannelUpdate builder.
func (_u *CustomerChannelUpdateOne) Where(ps ...predicate.CustomerChannel) *CustomerChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomerChannelUpdateOne) Select(field string, fields ...string) *CustomerChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomerChannel entity.
func (_u *CustomerChannelUpdateOne) Save(ctx context.Context) (*CustomerChannel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerChannelUpdateOne) SaveX(ctx context.Context) *CustomerChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomerChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomerChannelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customerchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomerChannelUpdateOne) check() error {
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomerChannel.customer"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomerChannel.channel"`)
	}
	return nil
}

func (_u *CustomerChannelUpdateOne) sqlSave(ctx context.Context) (_node *CustomerChannel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customerchannel.Table, customerchannel.Columns, sqlgraph.NewFieldSpec(customerchannel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CustomerChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customerchannel.FieldID)
		for _, f := range fields {
			if !customerchannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != customerchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customerchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(customerchannel.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRole(); ok {
		_spec.AddField(customerchannel.FieldRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(customerchannel.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, customerchannel.FieldPermissions, value)
		})
	}
	if _u.mutation.PermissionsCleared() {
		_spec.ClearField(customerchannel.FieldPermissions, field.TypeJSON)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerchannel.CustomerTable,
			Columns: []string{customerchannel.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerchannel.CustomerTable,
			Columns: []string{customerchannel.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerchannel.ChannelTable,
			Columns: []string{customerchannel.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customerchannel.ChannelTable,
			Columns: []string{customerchannel.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CustomerChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customerchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
