// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customer"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customerbrief"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customerchannel"
	"github.com/wickedv43/TAM-backend/internal/database/ent/deal"
)

// CustomerCreate is the builder for creating a Customer entity.
type CustomerCreate struct {
	config
	mutation *CustomerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomerCreate) SetCreatedAt(v time.Time) *CustomerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableCreatedAt(v *time.Time) *CustomerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomerCreate) SetUpdatedAt(v time.Time) *CustomerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableUpdatedAt(v *time.Time) *CustomerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTgID sets the "tg_id" field.
func (_c *CustomerCreate) SetTgID(v int64) *CustomerCreate {
	_c.mutation.SetTgID(v)
	return _c
}

// SetTgUsername sets the "tg_username" field.
func (_c *CustomerCreate) SetTgUsername(v string) *CustomerCreate {
	_c.mutation.SetTgUsername(v)
	return _c
}

// SetNillableTgUsername sets the "tg_username" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTgUsername(v *string) *CustomerCreate {
	if v != nil {
		_c.SetTgUsername(*v)
	}
	return _c
}

// SetTgFirstname sets the "tg_firstname" field.
func (_c *CustomerCreate) SetTgFirstname(v string) *CustomerCreate {
	_c.mutation.SetTgFirstname(v)
	return _c
}

// SetNillableTgFirstname sets the "tg_firstname" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTgFirstname(v *string) *CustomerCreate {
	if v != nil {
		_c.SetTgFirstname(*v)
	}
	return _c
}

// SetTgLastname sets the "tg_lastname" field.
func (_c *CustomerCreate) SetTgLastname(v string) *CustomerCreate {
	_c.mutation.SetTgLastname(v)
	return _c
}

// SetNillableTgLastname sets the "tg_lastname" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTgLastname(v *string) *CustomerCreate {
	if v != nil {
		_c.SetTgLastname(*v)
	}
	return _c
}

// SetTgLanguage sets the "tg_language" field.
func (_c *CustomerCreate) SetTgLanguage(v string) *CustomerCreate {
	_c.mutation.SetTgLanguage(v)
	return _c
}

// SetNillableTgLanguage sets the "tg_language" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTgLanguage(v *string) *CustomerCreate {
	if v != nil {
		_c.SetTgLanguage(*v)
	}
	return _c
}

// SetTgPicture sets the "tg_picture" field.
func (_c *CustomerCreate) SetTgPicture(v string) *CustomerCreate {
	_c.mutation.SetTgPicture(v)
	return _c
}

// SetNillableTgPicture sets the "tg_picture" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTgPicture(v *string) *CustomerCreate {
	if v != nil {
		_c.SetTgPicture(*v)
	}
	return _c
}

// SetTgIsPremium sets the "tg_is_premium" field.
func (_c *CustomerCreate) SetTgIsPremium(v bool) *CustomerCreate {
	_c.mutation.SetTgIsPremium(v)
	return _c
}

// SetNillableTgIsPremium sets the "tg_is_premium" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTgIsPremium(v *bool) *CustomerCreate {
	if v != nil {
		_c.SetTgIsPremium(*v)
	}
	return _c
}

// SetTgIsAllowPm sets the "tg_is_allow_pm" field.
func (_c *CustomerCreate) SetTgIsAllowPm(v bool) *CustomerCreate {
	_c.mutation.SetTgIsAllowPm(v)
	return _c
}

// SetNillableTgIsAllowPm sets the "tg_is_allow_pm" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTgIsAllowPm(v *bool) *CustomerCreate {
	if v != nil {
		_c.SetTgIsAllowPm(*v)
	}
	return _c
}

// SetReferrerTgID sets the "referrer_tg_id" field.
func (_c *CustomerCreate) SetReferrerTgID(v int64) *CustomerCreate {
	_c.mutation.SetReferrerTgID(v)
	return _c
}

// SetNillableReferrerTgID sets the "referrer_tg_id" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableReferrerTgID(v *int64) *CustomerCreate {
	if v != nil {
		_c.SetReferrerTgID(*v)
	}
	return _c
}

// SetWalletHdID sets the "wallet_hd_id" field.
func (_c *CustomerCreate) SetWalletHdID(v int64) *CustomerCreate {
	_c.mutation.SetWalletHdID(v)
	return _c
}

// SetNillableWalletHdID sets the "wallet_hd_id" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableWalletHdID(v *int64) *CustomerCreate {
	if v != nil {
		_c.SetWalletHdID(*v)
	}
	return _c
}

// SetAddressBounceable sets the "address_bounceable" field.
func (_c *CustomerCreate) SetAddressBounceable(v string) *CustomerCreate {
	_c.mutation.SetAddressBounceable(v)
	return _c
}

// SetNillableAddressBounceable sets the "address_bounceable" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableAddressBounceable(v *string) *CustomerCreate {
	if v != nil {
		_c.SetAddressBounceable(*v)
	}
	return _c
}

// SetAddressNonbounceable sets the "address_nonbounceable" field.
func (_c *CustomerCreate) SetAddressNonbounceable(v string) *CustomerCreate {
	_c.mutation.SetAddressNonbounceable(v)
	return _c
}

// SetNillableAddressNonbounceable sets the "address_nonbounceable" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableAddressNonbounceable(v *string) *CustomerCreate {
	if v != nil {
		_c.SetAddressNonbounceable(*v)
	}
	return _c
}

// SetTonBalance sets the "ton_balance" field.
func (_c *CustomerCreate) SetTonBalance(v float64) *CustomerCreate {
	_c.mutation.SetTonBalance(v)
	return _c
}

// SetNillableTonBalance sets the "ton_balance" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTonBalance(v *float64) *CustomerCreate {
	if v != nil {
		_c.SetTonBalance(*v)
	}
	return _c
}

// SetTonBalanceLocked sets the "ton_balance_locked" field.
func (_c *CustomerCreate) SetTonBalanceLocked(v float64) *CustomerCreate {
	_c.mutation.SetTonBalanceLocked(v)
	return _c
}

// SetNillableTonBalanceLocked sets the "ton_balance_locked" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableTonBalanceLocked(v *float64) *CustomerCreate {
	if v != nil {
		_c.SetTonBalanceLocked(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CustomerCreate) SetStatus(v int) *CustomerCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableStatus(v *int) *CustomerCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CustomerCreate) SetID(v uuid.UUID) *CustomerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableID(v *uuid.UUID) *CustomerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddCustomerChannelIDs adds the "customer_channels" edge to the CustomerChannel entity by IDs.
func (_c *CustomerCreate) AddCustomerChannelIDs(ids ...uuid.UUID) *CustomerCreate {
	_c.mutation.AddCustomerChannelIDs(ids...)
	return _c
}

// AddCustomerChannels adds the "customer_channels" edges to the CustomerChannel entity.
func (_c *CustomerCreate) AddCustomerChannels(v ...*CustomerChannel) *CustomerCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCustomerChannelIDs(ids...)
}

// AddCustomerBriefIDs adds the "customer_briefs" edge to the CustomerBrief entity by IDs.
func (_c *CustomerCreate) AddCustomerBriefIDs(ids ...uuid.UUID) *CustomerCreate {
	_c.mutation.AddCustomerBriefIDs(ids...)
	return _c
}

// AddCustomerBriefs adds the "customer_briefs" edges to the CustomerBrief entity.
func (_c *CustomerCreate) AddCustomerBriefs(v ...*CustomerBrief) *CustomerCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCustomerBriefIDs(ids...)
}

// AddAdvertiserDealIDs adds the "advertiser_deals" edge to the Deal entity by IDs.
func (_c *CustomerCreate) AddAdvertiserDealIDs(ids ...uuid.UUID) *CustomerCreate {
	_c.mutation.AddAdvertiserDealIDs(ids...)
	return _c
}

// AddAdvertiserDeals adds the "advertiser_deals" edges to the Deal entity.
func (_c *CustomerCreate) AddAdvertiserDeals(v ...*Deal) *CustomerCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAdvertiserDealIDs(ids...)
}

// AddManagedDealIDs adds the "managed_deals" edge to the Deal entity by IDs.
func (_c *CustomerCreate) AddManagedDealIDs(ids ...uuid.UUID) *CustomerCreate {
	_c.mutation.AddManagedDealIDs(ids...)
	return _c
}

// AddManagedDeals adds the "managed_deals" edges to the Deal entity.
func (_c *CustomerCreate) AddManagedDeals(v ...*Deal) *CustomerCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddManagedDealIDs(ids...)
}

// Mutation returns the CustomerMutation object of the builder.
func (_c *CustomerCreate) Mutation() *CustomerMutation {
	return _c.mutation
}

// Save creates the Customer in the database.
func (_c *CustomerCreate) Save(ctx context.Context) (*Customer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomerCreate) SaveX(ctx context.Context) *Customer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := customer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := customer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TgIsPremium(); !ok {
		v := customer.DefaultTgIsPremium
		_c.mutation.SetTgIsPremium(v)
	}
	if _, ok := _c.mutation.TgIsAllowPm(); !ok {
		v := customer.DefaultTgIsAllowPm
		_c.mutation.SetTgIsAllowPm(v)
	}
	if _, ok := _c.mutation.TonBalance(); !ok {
		v := customer.DefaultTonBalance
		_c.mutation.SetTonBalance(v)
	}
	if _, ok := _c.mutation.TonBalanceLocked(); !ok {
		v := customer.DefaultTonBalanceLocked
		_c.mutation.SetTonBalanceLocked(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := customer.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := customer.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Customer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Customer.updated_at"`)}
	}
	if _, ok := _c.mutation.TgID(); !ok {
		return &ValidationError{Name: "tg_id", err: errors.New(`ent: missing required field "Customer.tg_id"`)}
	}
	if _, ok := _c.mutation.TgIsPremium(); !ok {
		return &ValidationError{Name: "tg_is_premium", err: errors.New(`ent: missing required field "Customer.tg_is_premium"`)}
	}
	if _, ok := _c.mutation.TgIsAllowPm(); !ok {
		return &ValidationError{Name: "tg_is_allow_pm", err: errors.New(`ent: missing required field "Customer.tg_is_allow_pm"`)}
	}
	if _, ok := _c.mutation.TonBalance(); !ok {
		return &ValidationError{Name: "ton_balance", err: errors.New(`ent: missing required field "Customer.ton_balance"`)}
	}
	if _, ok := _c.mutation.TonBalanceLocked(); !ok {
		return &ValidationError{Name: "ton_balance_locked", err: errors.New(`ent: missing required field "Customer.ton_balance_locked"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Customer.status"`)}
	}
	return nil
}

func (_c *CustomerCreate) sqlSave(ctx context.Context) (*Customer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomerCreate) createSpec() (*Customer, *sqlgraph.CreateSpec) {
	var (
		_node = &Customer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customer.Table, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(customer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(customer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TgID(); ok {
		_spec.SetField(customer.FieldTgID, field.TypeInt64, value)
		_node.TgID = value
	}
	if value, ok := _c.mutation.TgUsername(); ok {
		_spec.SetField(customer.FieldTgUsername, field.TypeString, value)
		_node.TgUsername = value
	}
	if value, ok := _c.mutation.TgFirstname(); ok {
		_spec.SetField(customer.FieldTgFirstname, field.TypeString, value)
		_node.TgFirstname = value
	}
	if value, ok := _c.mutation.TgLastname(); ok {
		_spec.SetField(customer.FieldTgLastname, field.TypeString, value)
		_node.TgLastname = value
	}
	if value, ok := _c.mutation.TgLanguage(); ok {
		_spec.SetField(customer.FieldTgLanguage, field.TypeString, value)
		_node.TgLanguage = value
	}
	if value, ok := _c.mutation.TgPicture(); ok {
		_spec.SetField(customer.FieldTgPicture, field.TypeString, value)
		_node.TgPicture = value
	}
	if value, ok := _c.mutation.TgIsPremium(); ok {
		_spec.SetField(customer.FieldTgIsPremium, field.TypeBool, value)
		_node.TgIsPremium = value
	}
	if value, ok := _c.mutation.TgIsAllowPm(); ok {
		_spec.SetField(customer.FieldTgIsAllowPm, field.TypeBool, value)
		_node.TgIsAllowPm = value
	}
	if value, ok := _c.mutation.ReferrerTgID(); ok {
		_spec.SetField(customer.FieldReferrerTgID, field.TypeInt64, value)
		_node.ReferrerTgID = value
	}
	if value, ok := _c.mutation.WalletHdID(); ok {
		_spec.SetField(customer.FieldWalletHdID, field.TypeInt64, value)
		_node.WalletHdID = value
	}
	if value, ok := _c.mutation.AddressBounceable(); ok {
		_spec.SetField(customer.FieldAddressBounceable, field.TypeString, value)
		_node.AddressBounceable = value
	}
	if value, ok := _c.mutation.AddressNonbounceable(); ok {
		_spec.SetField(customer.FieldAddressNonbounceable, field.TypeString, value)
		_node.AddressNonbounceable = value
	}
	if value, ok := _c.mutation.TonBalance(); ok {
		_spec.SetField(customer.FieldTonBalance, field.TypeFloat64, value)
		_node.TonBalance = value
	}
	if value, ok := _c.mutation.TonBalanceLocked(); ok {
		_spec.SetField(customer.FieldTonBalanceLocked, field.TypeFloat64, value)
		_node.TonBalanceLocked = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(customer.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if nodes := _c.mutation.CustomerChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.CustomerChannelsTable,
			Columns: []string{customer.CustomerChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customerchannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomerBriefsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.CustomerBriefsTable,
			Columns: []string{customer.CustomerBriefsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customerbrief.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AdvertiserDealsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.AdvertiserDealsTable,
			Columns: []string{customer.AdvertiserDealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ManagedDealsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.ManagedDealsTable,
			Columns: []string{customer.ManagedDealsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Customer.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomerCreate) OnConflict(opts ...sql.ConflictOption) *CustomerUpsertOne {
	_c.conflict = opts
	return &CustomerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomerCreate) OnConflictColumns(columns ...string) *CustomerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomerUpsertOne{
		create: _c,
	}
}

type (
	// CustomerUpsertOne is the builder for "upsert"-ing
	//  one Customer node.
	CustomerUpsertOne struct {
		create *CustomerCreate
	}

	// CustomerUpsert is the "OnConflict" setter.
	CustomerUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *CustomerUpsert) SetCreatedAt(v time.Time) *CustomerUpsert {
	u.Set(customer.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateCreatedAt() *CustomerUpsert {
	u.SetExcluded(customer.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerUpsert) SetUpdatedAt(v time.Time) *CustomerUpsert {
	u.Set(customer.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateUpdatedAt() *CustomerUpsert {
	u.SetExcluded(customer.FieldUpdatedAt)
	return u
}

// SetTgID sets the "tg_id" field.
func (u *CustomerUpsert) SetTgID(v int64) *CustomerUpsert {
	u.Set(customer.FieldTgID, v)
	return u
}

// UpdateTgID sets the "tg_id" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTgID() *CustomerUpsert {
	u.SetExcluded(customer.FieldTgID)
	return u
}

// AddTgID adds v to the "tg_id" field.
func (u *CustomerUpsert) AddTgID(v int64) *CustomerUpsert {
	u.Add(customer.FieldTgID, v)
	return u
}

// SetTgUsername sets the "tg_username" field.
func (u *CustomerUpsert) SetTgUsername(v string) *CustomerUpsert {
	u.Set(customer.FieldTgUsername, v)
	return u
}

// UpdateTgUsername sets the "tg_username" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTgUsername() *CustomerUpsert {
	u.SetExcluded(customer.FieldTgUsername)
	return u
}

// ClearTgUsername clears the value of the "tg_username" field.
func (u *CustomerUpsert) ClearTgUsername() *CustomerUpsert {
	u.SetNull(customer.FieldTgUsername)
	return u
}

// SetTgFirstname sets the "tg_firstname" field.
func (u *CustomerUpsert) SetTgFirstname(v string) *CustomerUpsert {
	u.Set(customer.FieldTgFirstname, v)
	return u
}

// UpdateTgFirstname sets the "tg_firstname" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTgFirstname() *CustomerUpsert {
	u.SetExcluded(customer.FieldTgFirstname)
	return u
}

// ClearTgFirstname clears the value of the "tg_firstname" field.
func (u *CustomerUpsert) ClearTgFirstname() *CustomerUpsert {
	u.SetNull(customer.FieldTgFirstname)
	return u
}

// SetTgLastname sets the "tg_lastname" field.
func (u *CustomerUpsert) SetTgLastname(v string) *CustomerUpsert {
	u.Set(customer.FieldTgLastname, v)
	return u
}

// UpdateTgLastname sets the "tg_lastname" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTgLastname() *CustomerUpsert {
	u.SetExcluded(customer.FieldTgLastname)
	return u
}

// ClearTgLastname clears the value of the "tg_lastname" field.
func (u *CustomerUpsert) ClearTgLastname() *CustomerUpsert {
	u.SetNull(customer.FieldTgLastname)
	return u
}

// SetTgLanguage sets the "tg_language" field.
func (u *CustomerUpsert) SetTgLanguage(v string) *CustomerUpsert {
	u.Set(customer.FieldTgLanguage, v)
	return u
}

// UpdateTgLanguage sets the "tg_language" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTgLanguage() *CustomerUpsert {
	u.SetExcluded(customer.FieldTgLanguage)
	return u
}

// ClearTgLanguage clears the value of the "tg_language" field.
func (u *CustomerUpsert) ClearTgLanguage() *CustomerUpsert {
	u.SetNull(customer.FieldTgLanguage)
	return u
}

// SetTgPicture sets the "tg_picture" field.
func (u *CustomerUpsert) SetTgPicture(v string) *CustomerUpsert {
	u.Set(customer.FieldTgPicture, v)
	return u
}

// UpdateTgPicture sets the "tg_picture" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTgPicture() *CustomerUpsert {
	u.SetExcluded(customer.FieldTgPicture)
	return u
}

// ClearTgPicture clears the value of the "tg_picture" field.
func (u *CustomerUpsert) ClearTgPicture() *CustomerUpsert {
	u.SetNull(customer.FieldTgPicture)
	return u
}

// SetTgIsPremium sets the "tg_is_premium" field.
func (u *CustomerUpsert) SetTgIsPremium(v bool) *CustomerUpsert {
	u.Set(customer.FieldTgIsPremium, v)
	return u
}

// UpdateTgIsPremium sets the "tg_is_premium" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTgIsPremium() *CustomerUpsert {
	u.SetExcluded(customer.FieldTgIsPremium)
	return u
}

// SetTgIsAllowPm sets the "tg_is_allow_pm" field.
func (u *CustomerUpsert) SetTgIsAllowPm(v bool) *CustomerUpsert {
	u.Set(customer.FieldTgIsAllowPm, v)
	return u
}

// UpdateTgIsAllowPm sets the "tg_is_allow_pm" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTgIsAllowPm() *CustomerUpsert {
	u.SetExcluded(customer.FieldTgIsAllowPm)
	return u
}

// SetReferrerTgID sets the "referrer_tg_id" field.
func (u *CustomerUpsert) SetReferrerTgID(v int64) *CustomerUpsert {
	u.Set(customer.FieldReferrerTgID, v)
	return u
}

// UpdateReferrerTgID sets the "referrer_tg_id" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateReferrerTgID() *CustomerUpsert {
	u.SetExcluded(customer.FieldReferrerTgID)
	return u
}

// AddReferrerTgID adds v to the "referrer_tg_id" field.
func (u *CustomerUpsert) AddReferrerTgID(v int64) *CustomerUpsert {
	u.Add(customer.FieldReferrerTgID, v)
	return u
}

// ClearReferrerTgID clears the value of the "referrer_tg_id" field.
func (u *CustomerUpsert) ClearReferrerTgID() *CustomerUpsert {
	u.SetNull(customer.FieldReferrerTgID)
	return u
}

// SetWalletHdID sets the "wallet_hd_id" field.
func (u *CustomerUpsert) SetWalletHdID(v int64) *CustomerUpsert {
	u.Set(customer.FieldWalletHdID, v)
	return u
}

// UpdateWalletHdID sets the "wallet_hd_id" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateWalletHdID() *CustomerUpsert {
	u.SetExcluded(customer.FieldWalletHdID)
	return u
}

// AddWalletHdID adds v to the "wallet_hd_id" field.
func (u *CustomerUpsert) AddWalletHdID(v int64) *CustomerUpsert {
	u.Add(customer.FieldWalletHdID, v)
	return u
}

// ClearWalletHdID clears the value of the "wallet_hd_id" field.
func (u *CustomerUpsert) ClearWalletHdID() *CustomerUpsert {
	u.SetNull(customer.FieldWalletHdID)
	return u
}

// SetAddressBounceable sets the "address_bounceable" field.
func (u *CustomerUpsert) SetAddressBounceable(v string) *CustomerUpsert {
	u.Set(customer.FieldAddressBounceable, v)
	return u
}

// UpdateAddressBounceable sets the "address_bounceable" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateAddressBounceable() *CustomerUpsert {
	u.SetExcluded(customer.FieldAddressBounceable)
	return u
}

// ClearAddressBounceable clears the value of the "address_bounceable" field.
func (u *CustomerUpsert) ClearAddressBounceable() *CustomerUpsert {
	u.SetNull(customer.FieldAddressBounceable)
	return u
}

// SetAddressNonbounceable sets the "address_nonbounceable" field.
func (u *CustomerUpsert) SetAddressNonbounceable(v string) *CustomerUpsert {
	u.Set(customer.FieldAddressNonbounceable, v)
	return u
}

// UpdateAddressNonbounceable sets the "address_nonbounceable" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateAddressNonbounceable() *CustomerUpsert {
	u.SetExcluded(customer.FieldAddressNonbounceable)
	return u
}

// ClearAddressNonbounceable clears the value of the "address_nonbounceable" field.
func (u *CustomerUpsert) ClearAddressNonbounceable() *CustomerUpsert {
	u.SetNull(customer.FieldAddressNonbounceable)
	return u
}

// SetTonBalance sets the "ton_balance" field.
func (u *CustomerUpsert) SetTonBalance(v float64) *CustomerUpsert {
	u.Set(customer.FieldTonBalance, v)
	return u
}

// UpdateTonBalance sets the "ton_balance" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTonBalance() *CustomerUpsert {
	u.SetExcluded(customer.FieldTonBalance)
	return u
}

// AddTonBalance adds v to the "ton_balance" field.
func (u *CustomerUpsert) AddTonBalance(v float64) *CustomerUpsert {
	u.Add(customer.FieldTonBalance, v)
	return u
}

// SetTonBalanceLocked sets the "ton_balance_locked" field.
func (u *CustomerUpsert) SetTonBalanceLocked(v float64) *CustomerUpsert {
	u.Set(customer.FieldTonBalanceLocked, v)
	return u
}

// UpdateTonBalanceLocked sets the "ton_balance_locked" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateTonBalanceLocked() *CustomerUpsert {
	u.SetExcluded(customer.FieldTonBalanceLocked)
	return u
}

// AddTonBalanceLocked adds v to the "ton_balance_locked" field.
func (u *CustomerUpsert) AddTonBalanceLocked(v float64) *CustomerUpsert {
	u.Add(customer.FieldTonBalanceLocked, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CustomerUpsert) SetStatus(v int) *CustomerUpsert {
	u.Set(customer.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CustomerUpsert) UpdateStatus() *CustomerUpsert {
	u.SetExcluded(customer.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *CustomerUpsert) AddStatus(v int) *CustomerUpsert {
	u.Add(customer.FieldStatus, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerUpsertOne) UpdateNewValues() *CustomerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(customer.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Customer.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomerUpsertOne) Ignore() *CustomerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerUpsertOne) DoNothing() *CustomerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerCreate.OnConflict
// documentation for more info.
func (u *CustomerUpsertOne) Update(set func(*CustomerUpsert)) *CustomerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CustomerUpsertOne) SetCreatedAt(v time.Time) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateCreatedAt() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerUpsertOne) SetUpdatedAt(v time.Time) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateUpdatedAt() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTgID sets the "tg_id" field.
func (u *CustomerUpsertOne) SetTgID(v int64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgID(v)
	})
}

// AddTgID adds v to the "tg_id" field.
func (u *CustomerUpsertOne) AddTgID(v int64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddTgID(v)
	})
}

// UpdateTgID sets the "tg_id" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTgID() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgID()
	})
}

// SetTgUsername sets the "tg_username" field.
func (u *CustomerUpsertOne) SetTgUsername(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgUsername(v)
	})
}

// UpdateTgUsername sets the "tg_username" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTgUsername() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgUsername()
	})
}

// ClearTgUsername clears the value of the "tg_username" field.
func (u *CustomerUpsertOne) ClearTgUsername() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgUsername()
	})
}

// SetTgFirstname sets the "tg_firstname" field.
func (u *CustomerUpsertOne) SetTgFirstname(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgFirstname(v)
	})
}

// UpdateTgFirstname sets the "tg_firstname" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTgFirstname() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgFirstname()
	})
}

// ClearTgFirstname clears the value of the "tg_firstname" field.
func (u *CustomerUpsertOne) ClearTgFirstname() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgFirstname()
	})
}

// SetTgLastname sets the "tg_lastname" field.
func (u *CustomerUpsertOne) SetTgLastname(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgLastname(v)
	})
}

// UpdateTgLastname sets the "tg_lastname" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTgLastname() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgLastname()
	})
}

// ClearTgLastname clears the value of the "tg_lastname" field.
func (u *CustomerUpsertOne) ClearTgLastname() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgLastname()
	})
}

// SetTgLanguage sets the "tg_language" field.
func (u *CustomerUpsertOne) SetTgLanguage(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgLanguage(v)
	})
}

// UpdateTgLanguage sets the "tg_language" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTgLanguage() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgLanguage()
	})
}

// ClearTgLanguage clears the value of the "tg_language" field.
func (u *CustomerUpsertOne) ClearTgLanguage() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgLanguage()
	})
}

// SetTgPicture sets the "tg_picture" field.
func (u *CustomerUpsertOne) SetTgPicture(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgPicture(v)
	})
}

// UpdateTgPicture sets the "tg_picture" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTgPicture() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgPicture()
	})
}

// ClearTgPicture clears the value of the "tg_picture" field.
func (u *CustomerUpsertOne) ClearTgPicture() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgPicture()
	})
}

// SetTgIsPremium sets the "tg_is_premium" field.
func (u *CustomerUpsertOne) SetTgIsPremium(v bool) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgIsPremium(v)
	})
}

// UpdateTgIsPremium sets the "tg_is_premium" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTgIsPremium() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgIsPremium()
	})
}

// SetTgIsAllowPm sets the "tg_is_allow_pm" field.
func (u *CustomerUpsertOne) SetTgIsAllowPm(v bool) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgIsAllowPm(v)
	})
}

// UpdateTgIsAllowPm sets the "tg_is_allow_pm" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTgIsAllowPm() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgIsAllowPm()
	})
}

// SetReferrerTgID sets the "referrer_tg_id" field.
func (u *CustomerUpsertOne) SetReferrerTgID(v int64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetReferrerTgID(v)
	})
}

// AddReferrerTgID adds v to the "referrer_tg_id" field.
func (u *CustomerUpsertOne) AddReferrerTgID(v int64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddReferrerTgID(v)
	})
}

// UpdateReferrerTgID sets the "referrer_tg_id" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateReferrerTgID() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateReferrerTgID()
	})
}

// ClearReferrerTgID clears the value of the "referrer_tg_id" field.
func (u *CustomerUpsertOne) ClearReferrerTgID() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearReferrerTgID()
	})
}

// SetWalletHdID sets the "wallet_hd_id" field.
func (u *CustomerUpsertOne) SetWalletHdID(v int64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetWalletHdID(v)
	})
}

// AddWalletHdID adds v to the "wallet_hd_id" field.
func (u *CustomerUpsertOne) AddWalletHdID(v int64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddWalletHdID(v)
	})
}

// UpdateWalletHdID sets the "wallet_hd_id" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateWalletHdID() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateWalletHdID()
	})
}

// ClearWalletHdID clears the value of the "wallet_hd_id" field.
func (u *CustomerUpsertOne) ClearWalletHdID() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearWalletHdID()
	})
}

// SetAddressBounceable sets the "address_bounceable" field.
func (u *CustomerUpsertOne) SetAddressBounceable(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetAddressBounceable(v)
	})
}

// UpdateAddressBounceable sets the "address_bounceable" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateAddressBounceable() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateAddressBounceable()
	})
}

// ClearAddressBounceable clears the value of the "address_bounceable" field.
func (u *CustomerUpsertOne) ClearAddressBounceable() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearAddressBounceable()
	})
}

// SetAddressNonbounceable sets the "address_nonbounceable" field.
func (u *CustomerUpsertOne) SetAddressNonbounceable(v string) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetAddressNonbounceable(v)
	})
}

// UpdateAddressNonbounceable sets the "address_nonbounceable" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateAddressNonbounceable() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateAddressNonbounceable()
	})
}

// ClearAddressNonbounceable clears the value of the "address_nonbounceable" field.
func (u *CustomerUpsertOne) ClearAddressNonbounceable() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearAddressNonbounceable()
	})
}

// SetTonBalance sets the "ton_balance" field.
func (u *CustomerUpsertOne) SetTonBalance(v float64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTonBalance(v)
	})
}

// AddTonBalance adds v to the "ton_balance" field.
func (u *CustomerUpsertOne) AddTonBalance(v float64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddTonBalance(v)
	})
}

// UpdateTonBalance sets the "ton_balance" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTonBalance() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTonBalance()
	})
}

// SetTonBalanceLocked sets the "ton_balance_locked" field.
func (u *CustomerUpsertOne) SetTonBalanceLocked(v float64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTonBalanceLocked(v)
	})
}

// AddTonBalanceLocked adds v to the "ton_balance_locked" field.
func (u *CustomerUpsertOne) AddTonBalanceLocked(v float64) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddTonBalanceLocked(v)
	})
}

// UpdateTonBalanceLocked sets the "ton_balance_locked" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateTonBalanceLocked() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTonBalanceLocked()
	})
}

// SetStatus sets the "status" field.
func (u *CustomerUpsertOne) SetStatus(v int) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *CustomerUpsertOne) AddStatus(v int) *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CustomerUpsertOne) UpdateStatus() *CustomerUpsertOne {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *CustomerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomerUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CustomerUpsertOne.ID is not supported by MySQL driver. Use CustomerUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomerUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomerCreateBulk is the builder for creating many Customer entities in bulk.
type CustomerCreateBulk struct {
	config
	err      error
	builders []*CustomerCreate
	conflict []sql.ConflictOption
}

// Save creates the Customer entities in the database.
func (_c *CustomerCreateBulk) Save(ctx context.Context) ([]*Customer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Customer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomerCreateBulk) SaveX(ctx context.Context) []*Customer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Customer.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomerCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomerUpsertBulk {
	_c.conflict = opts
	return &CustomerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomerCreateBulk) OnConflictColumns(columns ...string) *CustomerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomerUpsertBulk{
		create: _c,
	}
}

// CustomerUpsertBulk is the builder for "upsert"-ing
// a bulk of Customer nodes.
type CustomerUpsertBulk struct {
	create *CustomerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerUpsertBulk) UpdateNewValues() *CustomerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(customer.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Customer.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomerUpsertBulk) Ignore() *CustomerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerUpsertBulk) DoNothing() *CustomerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerCreateBulk.OnConflict
// documentation for more info.
func (u *CustomerUpsertBulk) Update(set func(*CustomerUpsert)) *CustomerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CustomerUpsertBulk) SetCreatedAt(v time.Time) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateCreatedAt() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerUpsertBulk) SetUpdatedAt(v time.Time) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateUpdatedAt() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTgID sets the "tg_id" field.
func (u *CustomerUpsertBulk) SetTgID(v int64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgID(v)
	})
}

// AddTgID adds v to the "tg_id" field.
func (u *CustomerUpsertBulk) AddTgID(v int64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddTgID(v)
	})
}

// UpdateTgID sets the "tg_id" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTgID() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgID()
	})
}

// SetTgUsername sets the "tg_username" field.
func (u *CustomerUpsertBulk) SetTgUsername(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgUsername(v)
	})
}

// UpdateTgUsername sets the "tg_username" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTgUsername() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgUsername()
	})
}

// ClearTgUsername clears the value of the "tg_username" field.
func (u *CustomerUpsertBulk) ClearTgUsername() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgUsername()
	})
}

// SetTgFirstname sets the "tg_firstname" field.
func (u *CustomerUpsertBulk) SetTgFirstname(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgFirstname(v)
	})
}

// UpdateTgFirstname sets the "tg_firstname" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTgFirstname() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgFirstname()
	})
}

// ClearTgFirstname clears the value of the "tg_firstname" field.
func (u *CustomerUpsertBulk) ClearTgFirstname() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgFirstname()
	})
}

// SetTgLastname sets the "tg_lastname" field.
func (u *CustomerUpsertBulk) SetTgLastname(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgLastname(v)
	})
}

// UpdateTgLastname sets the "tg_lastname" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTgLastname() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgLastname()
	})
}

// ClearTgLastname clears the value of the "tg_lastname" field.
func (u *CustomerUpsertBulk) ClearTgLastname() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgLastname()
	})
}

// SetTgLanguage sets the "tg_language" field.
func (u *CustomerUpsertBulk) SetTgLanguage(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgLanguage(v)
	})
}

// UpdateTgLanguage sets the "tg_language" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTgLanguage() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgLanguage()
	})
}

// ClearTgLanguage clears the value of the "tg_language" field.
func (u *CustomerUpsertBulk) ClearTgLanguage() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgLanguage()
	})
}

// SetTgPicture sets the "tg_picture" field.
func (u *CustomerUpsertBulk) SetTgPicture(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgPicture(v)
	})
}

// UpdateTgPicture sets the "tg_picture" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTgPicture() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgPicture()
	})
}

// ClearTgPicture clears the value of the "tg_picture" field.
func (u *CustomerUpsertBulk) ClearTgPicture() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearTgPicture()
	})
}

// SetTgIsPremium sets the "tg_is_premium" field.
func (u *CustomerUpsertBulk) SetTgIsPremium(v bool) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgIsPremium(v)
	})
}

// UpdateTgIsPremium sets the "tg_is_premium" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTgIsPremium() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgIsPremium()
	})
}

// SetTgIsAllowPm sets the "tg_is_allow_pm" field.
func (u *CustomerUpsertBulk) SetTgIsAllowPm(v bool) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTgIsAllowPm(v)
	})
}

// UpdateTgIsAllowPm sets the "tg_is_allow_pm" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTgIsAllowPm() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTgIsAllowPm()
	})
}

// SetReferrerTgID sets the "referrer_tg_id" field.
func (u *CustomerUpsertBulk) SetReferrerTgID(v int64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetReferrerTgID(v)
	})
}

// AddReferrerTgID adds v to the "referrer_tg_id" field.
func (u *CustomerUpsertBulk) AddReferrerTgID(v int64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddReferrerTgID(v)
	})
}

// UpdateReferrerTgID sets the "referrer_tg_id" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateReferrerTgID() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateReferrerTgID()
	})
}

// ClearReferrerTgID clears the value of the "referrer_tg_id" field.
func (u *CustomerUpsertBulk) ClearReferrerTgID() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearReferrerTgID()
	})
}

// SetWalletHdID sets the "wallet_hd_id" field.
func (u *CustomerUpsertBulk) SetWalletHdID(v int64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetWalletHdID(v)
	})
}

// AddWalletHdID adds v to the "wallet_hd_id" field.
func (u *CustomerUpsertBulk) AddWalletHdID(v int64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddWalletHdID(v)
	})
}

// UpdateWalletHdID sets the "wallet_hd_id" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateWalletHdID() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateWalletHdID()
	})
}

// ClearWalletHdID clears the value of the "wallet_hd_id" field.
func (u *CustomerUpsertBulk) ClearWalletHdID() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearWalletHdID()
	})
}

// SetAddressBounceable sets the "address_bounceable" field.
func (u *CustomerUpsertBulk) SetAddressBounceable(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetAddressBounceable(v)
	})
}

// UpdateAddressBounceable sets the "address_bounceable" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateAddressBounceable() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateAddressBounceable()
	})
}

// ClearAddressBounceable clears the value of the "address_bounceable" field.
func (u *CustomerUpsertBulk) ClearAddressBounceable() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearAddressBounceable()
	})
}

// SetAddressNonbounceable sets the "address_nonbounceable" field.
func (u *CustomerUpsertBulk) SetAddressNonbounceable(v string) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetAddressNonbounceable(v)
	})
}

// UpdateAddressNonbounceable sets the "address_nonbounceable" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateAddressNonbounceable() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateAddressNonbounceable()
	})
}

// ClearAddressNonbounceable clears the value of the "address_nonbounceable" field.
func (u *CustomerUpsertBulk) ClearAddressNonbounceable() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.ClearAddressNonbounceable()
	})
}

// SetTonBalance sets the "ton_balance" field.
func (u *CustomerUpsertBulk) SetTonBalance(v float64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTonBalance(v)
	})
}

// AddTonBalance adds v to the "ton_balance" field.
func (u *CustomerUpsertBulk) AddTonBalance(v float64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddTonBalance(v)
	})
}

// UpdateTonBalance sets the "ton_balance" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTonBalance() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTonBalance()
	})
}

// SetTonBalanceLocked sets the "ton_balance_locked" field.
func (u *CustomerUpsertBulk) SetTonBalanceLocked(v float64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetTonBalanceLocked(v)
	})
}

// AddTonBalanceLocked adds v to the "ton_balance_locked" field.
func (u *CustomerUpsertBulk) AddTonBalanceLocked(v float64) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddTonBalanceLocked(v)
	})
}

// UpdateTonBalanceLocked sets the "ton_balance_locked" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateTonBalanceLocked() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateTonBalanceLocked()
	})
}

// SetStatus sets the "status" field.
func (u *CustomerUpsertBulk) SetStatus(v int) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *CustomerUpsertBulk) AddStatus(v int) *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CustomerUpsertBulk) UpdateStatus() *CustomerUpsertBulk {
	return u.Update(func(s *CustomerUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *CustomerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
