// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/channel"
	"github.com/wickedv43/TAM-backend/internal/database/ent/customer"
	"github.com/wickedv43/TAM-backend/internal/database/ent/deal"
	"github.com/wickedv43/TAM-backend/internal/database/ent/predicate"
)

// DealUpdate is the builder for updating Deal entities.
type DealUpdate struct {
	config
	hooks    []Hook
	mutation *DealMutation
}

// Where appends a list predicates to the DealUpdate builder.
func (_u *DealUpdate) Where(ps ...predicate.Deal) *DealUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DealUpdate) SetUpdatedAt(v time.Time) *DealUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *DealUpdate) SetChannelID(v uuid.UUID) *DealUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *DealUpdate) SetNillableChannelID(v *uuid.UUID) *DealUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetAdvertiserCustomerID sets the "advertiser_customer_id" field.
func (_u *DealUpdate) SetAdvertiserCustomerID(v uuid.UUID) *DealUpdate {
	_u.mutation.SetAdvertiserCustomerID(v)
	return _u
}

// SetNillableAdvertiserCustomerID sets the "advertiser_customer_id" field if the given value is not nil.
func (_u *DealUpdate) SetNillableAdvertiserCustomerID(v *uuid.UUID) *DealUpdate {
	if v != nil {
		_u.SetAdvertiserCustomerID(*v)
	}
	return _u
}

// SetChannelManagerID sets the "channel_manager_id" field.
func (_u *DealUpdate) SetChannelManagerID(v uuid.UUID) *DealUpdate {
	_u.mutation.SetChannelManagerID(v)
	return _u
}

// SetNillableChannelManagerID sets the "channel_manager_id" field if the given value is not nil.
func (_u *DealUpdate) SetNillableChannelManagerID(v *uuid.UUID) *DealUpdate {
	if v != nil {
		_u.SetChannelManagerID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DealUpdate) SetType(v int) *DealUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DealUpdate) SetNillableType(v *int) *DealUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *DealUpdate) AddType(v int) *DealUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DealUpdate) SetStatus(v int) *DealUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DealUpdate) SetNillableStatus(v *int) *DealUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DealUpdate) AddStatus(v int) *DealUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetStatusUpdatedAt sets the "status_updated_at" field.
func (_u *DealUpdate) SetStatusUpdatedAt(v time.Time) *DealUpdate {
	_u.mutation.SetStatusUpdatedAt(v)
	return _u
}

// SetNillableStatusUpdatedAt sets the "status_updated_at" field if the given value is not nil.
func (_u *DealUpdate) SetNillableStatusUpdatedAt(v *time.Time) *DealUpdate {
	if v != nil {
		_u.SetStatusUpdatedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DealUpdate) SetExpiresAt(v time.Time) *DealUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DealUpdate) SetNillableExpiresAt(v *time.Time) *DealUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *DealUpdate) SetTargetType(v string) *DealUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *DealUpdate) SetNillableTargetType(v *string) *DealUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *DealUpdate) SetTarget(v map[string]interface{}) *DealUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetPublicationTime sets the "publication_time" field.
func (_u *DealUpdate) SetPublicationTime(v time.Time) *DealUpdate {
	_u.mutation.SetPublicationTime(v)
	return _u
}

// SetNillablePublicationTime sets the "publication_time" field if the given value is not nil.
func (_u *DealUpdate) SetNillablePublicationTime(v *time.Time) *DealUpdate {
	if v != nil {
		_u.SetPublicationTime(*v)
	}
	return _u
}

// ClearPublicationTime clears the value of the "publication_time" field.
func (_u *DealUpdate) ClearPublicationTime() *DealUpdate {
	_u.mutation.ClearPublicationTime()
	return _u
}

// SetTopDeadline sets the "top_deadline" field.
func (_u *DealUpdate) SetTopDeadline(v time.Time) *DealUpdate {
	_u.mutation.SetTopDeadline(v)
	return _u
}

// SetNillableTopDeadline sets the "top_deadline" field if the given value is not nil.
func (_u *DealUpdate) SetNillableTopDeadline(v *time.Time) *DealUpdate {
	if v != nil {
		_u.SetTopDeadline(*v)
	}
	return _u
}

// ClearTopDeadline clears the value of the "top_deadline" field.
func (_u *DealUpdate) ClearTopDeadline() *DealUpdate {
	_u.mutation.ClearTopDeadline()
	return _u
}

// SetCommonDeadline sets the "common_deadline" field.
func (_u *DealUpdate) SetCommonDeadline(v time.Time) *DealUpdate {
	_u.mutation.SetCommonDeadline(v)
	return _u
}

// SetNillableCommonDeadline sets the "common_deadline" field if the given value is not nil.
func (_u *DealUpdate) SetNillableCommonDeadline(v *time.Time) *DealUpdate {
	if v != nil {
		_u.SetCommonDeadline(*v)
	}
	return _u
}

// ClearCommonDeadline clears the value of the "common_deadline" field.
func (_u *DealUpdate) ClearCommonDeadline() *DealUpdate {
	_u.mutation.ClearCommonDeadline()
	return _u
}

// SetTonPrice sets the "ton_price" field.
func (_u *DealUpdate) SetTonPrice(v float64) *DealUpdate {
	_u.mutation.ResetTonPrice()
	_u.mutation.SetTonPrice(v)
	return _u
}

// SetNillableTonPrice sets the "ton_price" field if the given value is not nil.
func (_u *DealUpdate) SetNillableTonPrice(v *float64) *DealUpdate {
	if v != nil {
		_u.SetTonPrice(*v)
	}
	return _u
}

// AddTonPrice adds value to the "ton_price" field.
func (_u *DealUpdate) AddTonPrice(v float64) *DealUpdate {
	_u.mutation.AddTonPrice(v)
	return _u
}

// SetBalanceRefunded sets the "balance_refunded" field.
func (_u *DealUpdate) SetBalanceRefunded(v bool) *DealUpdate {
	_u.mutation.SetBalanceRefunded(v)
	return _u
}

// SetNillableBalanceRefunded sets the "balance_refunded" field if the given value is not nil.
func (_u *DealUpdate) SetNillableBalanceRefunded(v *bool) *DealUpdate {
	if v != nil {
		_u.SetBalanceRefunded(*v)
	}
	return _u
}

// SetChannelPostIds sets the "channel_post_ids" field.
func (_u *DealUpdate) SetChannelPostIds(v []int) *DealUpdate {
	_u.mutation.SetChannelPostIds(v)
	return _u
}

// AppendChannelPostIds appends value to the "channel_post_ids" field.
func (_u *DealUpdate) AppendChannelPostIds(v []int) *DealUpdate {
	_u.mutation.AppendChannelPostIds(v)
	return _u
}

// ClearChannelPostIds clears the value of the "channel_post_ids" field.
func (_u *DealUpdate) ClearChannelPostIds() *DealUpdate {
	_u.mutation.ClearChannelPostIds()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *DealUpdate) SetChannel(v *Channel) *DealUpdate {
	return _u.SetChannelID(v.ID)
}

// SetAdvertiserID sets the "advertiser" edge to the Customer entity by ID.
func (_u *DealUpdate) SetAdvertiserID(id uuid.UUID) *DealUpdate {
	_u.mutation.SetAdvertiserID(id)
	return _u
}

// SetAdvertiser sets the "advertiser" edge to the Customer entity.
func (_u *DealUpdate) SetAdvertiser(v *Customer) *DealUpdate {
	return _u.SetAdvertiserID(v.ID)
}

// SetChannelManager sets the "channel_manager" edge to the Customer entity.
func (_u *DealUpdate) SetChannelManager(v *Customer) *DealUpdate {
	return _u.SetChannelManagerID(v.ID)
}

// Mutation returns the DealMutation object of the builder.
func (_u *DealUpdate) Mutation() *DealMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *DealUpdate) ClearChannel() *DealUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearAdvertiser clears the "advertiser" edge to the Customer entity.
func (_u *DealUpdate) ClearAdvertiser() *DealUpdate {
	_u.mutation.ClearAdvertiser()
	return _u
}

// ClearChannelManager clears the "channel_manager" edge to the Customer entity.
func (_u *DealUpdate) ClearChannelManager() *DealUpdate {
	_u.mutation.ClearChannelManager()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DealUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DealUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DealUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DealUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DealUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DealUpdate) check() error {
	if v, ok := _u.mutation.TonPrice(); ok {
		if err := deal.TonPriceValidator(v); err != nil {
			return &ValidationError{Name: "ton_price", err: fmt.Errorf(`ent: validator failed for field "Deal.ton_price": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deal.channel"`)
	}
	if _u.mutation.AdvertiserCleared() && len(_u.mutation.AdvertiserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deal.advertiser"`)
	}
	if _u.mutation.ChannelManagerCleared() && len(_u.mutation.ChannelManagerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deal.channel_manager"`)
	}
	return nil
}

func (_u *DealUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deal.Table, deal.Columns, sqlgraph.NewFieldSpec(deal.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(deal.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(deal.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deal.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(deal.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StatusUpdatedAt(); ok {
		_spec.SetField(deal.FieldStatusUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(deal.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(deal.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(deal.FieldTarget, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.PublicationTime(); ok {
		_spec.SetField(deal.FieldPublicationTime, field.TypeTime, value)
	}
	if _u.mutation.PublicationTimeCleared() {
		_spec.ClearField(deal.FieldPublicationTime, field.TypeTime)
	}
	if value, ok := _u.mutation.TopDeadline(); ok {
		_spec.SetField(deal.FieldTopDeadline, field.TypeTime, value)
	}
	if _u.mutation.TopDeadlineCleared() {
		_spec.ClearField(deal.FieldTopDeadline, field.TypeTime)
	}
	if value, ok := _u.mutation.CommonDeadline(); ok {
		_spec.SetField(deal.FieldCommonDeadline, field.TypeTime, value)
	}
	if _u.mutation.CommonDeadlineCleared() {
		_spec.ClearField(deal.FieldCommonDeadline, field.TypeTime)
	}
	if value, ok := _u.mutation.TonPrice(); ok {
		_spec.SetField(deal.FieldTonPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTonPrice(); ok {
		_spec.AddField(deal.FieldTonPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceRefunded(); ok {
		_spec.SetField(deal.FieldBalanceRefunded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ChannelPostIds(); ok {
		_spec.SetField(deal.FieldChannelPostIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChannelPostIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, deal.FieldChannelPostIds, value)
		})
	}
	if _u.mutation.ChannelPostIdsCleared() {
		_spec.ClearField(deal.FieldChannelPostIds, field.TypeJSON)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.ChannelTable,
			Columns: []string{deal.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.ChannelTable,
			Columns: []string{deal.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdvertiserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.AdvertiserTable,
			Columns: []string{deal.AdvertiserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdvertiserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.AdvertiserTable,
			Columns: []string{deal.AdvertiserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.ChannelManagerTable,
			Columns: []string{deal.ChannelManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.ChannelManagerTable,
			Columns: []string{deal.ChannelManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DealUpdateOne is the builder for updating a single Deal entity.
type DealUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DealMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DealUpdateOne) SetUpdatedAt(v time.Time) *DealUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *DealUpdateOne) SetChannelID(v uuid.UUID) *DealUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableChannelID(v *uuid.UUID) *DealUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetAdvertiserCustomerID sets the "advertiser_customer_id" field.
func (_u *DealUpdateOne) SetAdvertiserCustomerID(v uuid.UUID) *DealUpdateOne {
	_u.mutation.SetAdvertiserCustomerID(v)
	return _u
}

// SetNillableAdvertiserCustomerID sets the "advertiser_customer_id" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableAdvertiserCustomerID(v *uuid.UUID) *DealUpdateOne {
	if v != nil {
		_u.SetAdvertiserCustomerID(*v)
	}
	return _u
}

// SetChannelManagerID sets the "channel_manager_id" field.
func (_u *DealUpdateOne) SetChannelManagerID(v uuid.UUID) *DealUpdateOne {
	_u.mutation.SetChannelManagerID(v)
	return _u
}

// SetNillableChannelManagerID sets the "channel_manager_id" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableChannelManagerID(v *uuid.UUID) *DealUpdateOne {
	if v != nil {
		_u.SetChannelManagerID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DealUpdateOne) SetType(v int) *DealUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableType(v *int) *DealUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *DealUpdateOne) AddType(v int) *DealUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DealUpdateOne) SetStatus(v int) *DealUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableStatus(v *int) *DealUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DealUpdateOne) AddStatus(v int) *DealUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetStatusUpdatedAt sets the "status_updated_at" field.
func (_u *DealUpdateOne) SetStatusUpdatedAt(v time.Time) *DealUpdateOne {
	_u.mutation.SetStatusUpdatedAt(v)
	return _u
}

// SetNillableStatusUpdatedAt sets the "status_updated_at" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableStatusUpdatedAt(v *time.Time) *DealUpdateOne {
	if v != nil {
		_u.SetStatusUpdatedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DealUpdateOne) SetExpiresAt(v time.Time) *DealUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableExpiresAt(v *time.Time) *DealUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *DealUpdateOne) SetTargetType(v string) *DealUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableTargetType(v *string) *DealUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *DealUpdateOne) SetTarget(v map[string]interface{}) *DealUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetPublicationTime sets the "publication_time" field.
func (_u *DealUpdateOne) SetPublicationTime(v time.Time) *DealUpdateOne {
	_u.mutation.SetPublicationTime(v)
	return _u
}

// SetNillablePublicationTime sets the "publication_time" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillablePublicationTime(v *time.Time) *DealUpdateOne {
	if v != nil {
		_u.SetPublicationTime(*v)
	}
	return _u
}

// ClearPublicationTime clears the value of the "publication_time" field.
func (_u *DealUpdateOne) ClearPublicationTime() *DealUpdateOne {
	_u.mutation.ClearPublicationTime()
	return _u
}

// SetTopDeadline sets the "top_deadline" field.
func (_u *DealUpdateOne) SetTopDeadline(v time.Time) *DealUpdateOne {
	_u.mutation.SetTopDeadline(v)
	return _u
}

// SetNillableTopDeadline sets the "top_deadline" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableTopDeadline(v *time.Time) *DealUpdateOne {
	if v != nil {
		_u.SetTopDeadline(*v)
	}
	return _u
}

// ClearTopDeadline clears the value of the "top_deadline" field.
func (_u *DealUpdateOne) ClearTopDeadline() *DealUpdateOne {
	_u.mutation.ClearTopDeadline()
	return _u
}

// SetCommonDeadline sets the "common_deadline" field.
func (_u *DealUpdateOne) SetCommonDeadline(v time.Time) *DealUpdateOne {
	_u.mutation.SetCommonDeadline(v)
	return _u
}

// SetNillableCommonDeadline sets the "common_deadline" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableCommonDeadline(v *time.Time) *DealUpdateOne {
	if v != nil {
		_u.SetCommonDeadline(*v)
	}
	return _u
}

// ClearCommonDeadline clears the value of the "common_deadline" field.
func (_u *DealUpdateOne) ClearCommonDeadline() *DealUpdateOne {
	_u.mutation.ClearCommonDeadline()
	return _u
}

// SetTonPrice sets the "ton_price" field.
func (_u *DealUpdateOne) SetTonPrice(v float64) *DealUpdateOne {
	_u.mutation.ResetTonPrice()
	_u.mutation.SetTonPrice(v)
	return _u
}

// SetNillableTonPrice sets the "ton_price" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableTonPrice(v *float64) *DealUpdateOne {
	if v != nil {
		_u.SetTonPrice(*v)
	}
	return _u
}

// AddTonPrice adds value to the "ton_price" field.
func (_u *DealUpdateOne) AddTonPrice(v float64) *DealUpdateOne {
	_u.mutation.AddTonPrice(v)
	return _u
}

// SetBalanceRefunded sets the "balance_refunded" field.
func (_u *DealUpdateOne) SetBalanceRefunded(v bool) *DealUpdateOne {
	_u.mutation.SetBalanceRefunded(v)
	return _u
}

// SetNillableBalanceRefunded sets the "balance_refunded" field if the given value is not nil.
func (_u *DealUpdateOne) SetNillableBalanceRefunded(v *bool) *DealUpdateOne {
	if v != nil {
		_u.SetBalanceRefunded(*v)
	}
	return _u
}

// SetChannelPostIds sets the "channel_post_ids" field.
func (_u *DealUpdateOne) SetChannelPostIds(v []int) *DealUpdateOne {
	_u.mutation.SetChannelPostIds(v)
	return _u
}

// AppendChannelPostIds appends value to the "channel_post_ids" field.
func (_u *DealUpdateOne) AppendChannelPostIds(v []int) *DealUpdateOne {
	_u.mutation.AppendChannelPostIds(v)
	return _u
}

// ClearChannelPostIds clears the value of the "channel_post_ids" field.
func (_u *DealUpdateOne) ClearChannelPostIds() *DealUpdateOne {
	_u.mutation.ClearChannelPostIds()
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *DealUpdateOne) SetChannel(v *Channel) *DealUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetAdvertiserID sets the "advertiser" edge to the Customer entity by ID.
func (_u *DealUpdateOne) SetAdvertiserID(id uuid.UUID) *DealUpdateOne {
	_u.mutation.SetAdvertiserID(id)
	return _u
}

// SetAdvertiser sets the "advertiser" edge to the Customer entity.
func (_u *DealUpdateOne) SetAdvertiser(v *Customer) *DealUpdateOne {
	return _u.SetAdvertiserID(v.ID)
}

// SetChannelManager sets the "channel_manager" edge to the Customer entity.
func (_u *DealUpdateOne) SetChannelManager(v *Customer) *DealUpdateOne {
	return _u.SetChannelManagerID(v.ID)
}

// Mutation returns the DealMutation object of the builder.
func (_u *DealUpdateOne) Mutation() *DealMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *DealUpdateOne) ClearChannel() *DealUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearAdvertiser clears the "advertiser" edge to the Customer entity.
func (_u *DealUpdateOne) ClearAdvertiser() *DealUpdateOne {
	_u.mutation.ClearAdvertiser()
	return _u
}

// ClearChannelManager clears the "channel_manager" edge to the Customer entity.
func (_u *DealUpdateOne) ClearChannelManager() *DealUpdateOne {
	_u.mutation.ClearChannelManager()
	return _u
}

// Where appends a list predicates to the DealUpdate builder.
func (_u *DealUpdateOne) Where(ps ...predicate.Deal) *DealUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DealUpdateOne) Select(field string, fields ...string) *DealUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Deal entity.
func (_u *DealUpdateOne) Save(ctx context.Context) (*Deal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DealUpdateOne) SaveX(ctx context.Context) *Deal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DealUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DealUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DealUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DealUpdateOne) check() error {
	if v, ok := _u.mutation.TonPrice(); ok {
		if err := deal.TonPriceValidator(v); err != nil {
			return &ValidationError{Name: "ton_price", err: fmt.Errorf(`ent: validator failed for field "Deal.ton_price": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deal.channel"`)
	}
	if _u.mutation.AdvertiserCleared() && len(_u.mutation.AdvertiserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deal.advertiser"`)
	}
	if _u.mutation.ChannelManagerCleared() && len(_u.mutation.ChannelManagerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deal.channel_manager"`)
	}
	return nil
}

func (_u *DealUpdateOne) sqlSave(ctx context.Context) (_node *Deal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deal.Table, deal.Columns, sqlgraph.NewFieldSpec(deal.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deal.FieldID)
		for _, f := range fields {
			if !deal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(deal.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(deal.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deal.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(deal.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StatusUpdatedAt(); ok {
		_spec.SetField(deal.FieldStatusUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(deal.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(deal.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(deal.FieldTarget, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.PublicationTime(); ok {
		_spec.SetField(deal.FieldPublicationTime, field.TypeTime, value)
	}
	if _u.mutation.PublicationTimeCleared() {
		_spec.ClearField(deal.FieldPublicationTime, field.TypeTime)
	}
	if value, ok := _u.mutation.TopDeadline(); ok {
		_spec.SetField(deal.FieldTopDeadline, field.TypeTime, value)
	}
	if _u.mutation.TopDeadlineCleared() {
		_spec.ClearField(deal.FieldTopDeadline, field.TypeTime)
	}
	if value, ok := _u.mutation.CommonDeadline(); ok {
		_spec.SetField(deal.FieldCommonDeadline, field.TypeTime, value)
	}
	if _u.mutation.CommonDeadlineCleared() {
		_spec.ClearField(deal.FieldCommonDeadline, field.TypeTime)
	}
	if value, ok := _u.mutation.TonPrice(); ok {
		_spec.SetField(deal.FieldTonPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTonPrice(); ok {
		_spec.AddField(deal.FieldTonPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceRefunded(); ok {
		_spec.SetField(deal.FieldBalanceRefunded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ChannelPostIds(); ok {
		_spec.SetField(deal.FieldChannelPostIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChannelPostIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, deal.FieldChannelPostIds, value)
		})
	}
	if _u.mutation.ChannelPostIdsCleared() {
		_spec.ClearField(deal.FieldChannelPostIds, field.TypeJSON)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.ChannelTable,
			Columns: []string{deal.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.ChannelTable,
			Columns: []string{deal.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdvertiserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.AdvertiserTable,
			Columns: []string{deal.AdvertiserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdvertiserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.AdvertiserTable,
			Columns: []string{deal.AdvertiserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.ChannelManagerTable,
			Columns: []string{deal.ChannelManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deal.ChannelManagerTable,
			Columns: []string{deal.ChannelManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Deal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
