// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wickedv43/TAM-backend/internal/database/ent/indexerstate"
	"github.com/wickedv43/TAM-backend/internal/database/ent/predicate"
)

// IndexerStateDelete is the builder for deleting a IndexerState entity.
type IndexerStateDelete struct {
	config
	hooks    []Hook
	mutation *IndexerStateMutation
}

// Where appends a list predicates to the IndexerStateDelete builder.
func (_d *IndexerStateDelete) Where(ps ...predicate.IndexerState) *IndexerStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *IndexerStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IndexerStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *IndexerStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(indexerstate.Table, sqlgraph.NewFieldSpec(indexerstate.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// IndexerStateDeleteOne is the builder for deleting a single IndexerState entity.
type IndexerStateDeleteOne struct {
	_d *IndexerStateDelete
}

// Where appends a list predicates to the IndexerStateDelete builder.
func (_d *IndexerStateDeleteOne) Where(ps ...predicate.IndexerState) *IndexerStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *IndexerStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{indexerstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *IndexerStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
