// Code generated by ent, DO NOT EDIT.

package customer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the customer type in the database.
	Label = "customer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTgID holds the string denoting the tg_id field in the database.
	FieldTgID = "tg_id"
	// FieldTgUsername holds the string denoting the tg_username field in the database.
	FieldTgUsername = "tg_username"
	// FieldTgFirstname holds the string denoting the tg_firstname field in the database.
	FieldTgFirstname = "tg_firstname"
	// FieldTgLastname holds the string denoting the tg_lastname field in the database.
	FieldTgLastname = "tg_lastname"
	// FieldTgLanguage holds the string denoting the tg_language field in the database.
	FieldTgLanguage = "tg_language"
	// FieldTgPicture holds the string denoting the tg_picture field in the database.
	FieldTgPicture = "tg_picture"
	// FieldTgIsPremium holds the string denoting the tg_is_premium field in the database.
	FieldTgIsPremium = "tg_is_premium"
	// FieldTgIsAllowPm holds the string denoting the tg_is_allow_pm field in the database.
	FieldTgIsAllowPm = "tg_is_allow_pm"
	// FieldReferrerTgID holds the string denoting the referrer_tg_id field in the database.
	FieldReferrerTgID = "referrer_tg_id"
	// FieldWalletHdID holds the string denoting the wallet_hd_id field in the database.
	FieldWalletHdID = "wallet_hd_id"
	// FieldAddressBounceable holds the string denoting the address_bounceable field in the database.
	FieldAddressBounceable = "address_bounceable"
	// FieldAddressNonbounceable holds the string denoting the address_nonbounceable field in the database.
	FieldAddressNonbounceable = "address_nonbounceable"
	// FieldTonBalance holds the string denoting the ton_balance field in the database.
	FieldTonBalance = "ton_balance"
	// FieldTonBalanceLocked holds the string denoting the ton_balance_locked field in the database.
	FieldTonBalanceLocked = "ton_balance_locked"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeCustomerChannels holds the string denoting the customer_channels edge name in mutations.
	EdgeCustomerChannels = "customer_channels"
	// EdgeCustomerBriefs holds the string denoting the customer_briefs edge name in mutations.
	EdgeCustomerBriefs = "customer_briefs"
	// EdgeAdvertiserDeals holds the string denoting the advertiser_deals edge name in mutations.
	EdgeAdvertiserDeals = "advertiser_deals"
	// EdgeManagedDeals holds the string denoting the managed_deals edge name in mutations.
	EdgeManagedDeals = "managed_deals"
	// Table holds the table name of the customer in the database.
	Table = "customers"
	// CustomerChannelsTable is the table that holds the customer_channels relation/edge.
	CustomerChannelsTable = "customers_channels"
	// CustomerChannelsInverseTable is the table name for the CustomerChannel entity.
	// It exists in this package in order to avoid circular dependency with the "customerchannel" package.
	CustomerChannelsInverseTable = "customers_channels"
	// CustomerChannelsColumn is the table column denoting the customer_channels relation/edge.
	CustomerChannelsColumn = "customer_id"
	// CustomerBriefsTable is the table that holds the customer_briefs relation/edge.
	CustomerBriefsTable = "customers_briefs"
	// CustomerBriefsInverseTable is the table name for the CustomerBrief entity.
	// It exists in this package in order to avoid circular dependency with the "customerbrief" package.
	CustomerBriefsInverseTable = "customers_briefs"
	// CustomerBriefsColumn is the table column denoting the customer_briefs relation/edge.
	CustomerBriefsColumn = "customer_id"
	// AdvertiserDealsTable is the table that holds the advertiser_deals relation/edge.
	AdvertiserDealsTable = "deals"
	// AdvertiserDealsInverseTable is the table name for the Deal entity.
	// It exists in this package in order to avoid circular dependency with the "deal" package.
	AdvertiserDealsInverseTable = "deals"
	// AdvertiserDealsColumn is the table column denoting the advertiser_deals relation/edge.
	AdvertiserDealsColumn = "advertiser_customer_id"
	// ManagedDealsTable is the table that holds the managed_deals relation/edge.
	ManagedDealsTable = "deals"
	// ManagedDealsInverseTable is the table name for the Deal entity.
	// It exists in this package in order to avoid circular dependency with the "deal" package.
	ManagedDealsInverseTable = "deals"
	// ManagedDealsColumn is the table column denoting the managed_deals relation/edge.
	ManagedDealsColumn = "channel_manager_id"
)

// Columns holds all SQL columns for customer fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTgID,
	FieldTgUsername,
	FieldTgFirstname,
	FieldTgLastname,
	FieldTgLanguage,
	FieldTgPicture,
	FieldTgIsPremium,
	FieldTgIsAllowPm,
	FieldReferrerTgID,
	FieldWalletHdID,
	FieldAddressBounceable,
	FieldAddressNonbounceable,
	FieldTonBalance,
	FieldTonBalanceLocked,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTgIsPremium holds the default value on creation for the "tg_is_premium" field.
	DefaultTgIsPremium bool
	// DefaultTgIsAllowPm holds the default value on creation for the "tg_is_allow_pm" field.
	DefaultTgIsAllowPm bool
	// DefaultTonBalance holds the default value on creation for the "ton_balance" field.
	DefaultTonBalance float64
	// DefaultTonBalanceLocked holds the default value on creation for the "ton_balance_locked" field.
	DefaultTonBalanceLocked float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Customer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTgID orders the results by the tg_id field.
func ByTgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgID, opts...).ToFunc()
}

// ByTgUsername orders the results by the tg_username field.
func ByTgUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgUsername, opts...).ToFunc()
}

// ByTgFirstname orders the results by the tg_firstname field.
func ByTgFirstname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgFirstname, opts...).ToFunc()
}

// ByTgLastname orders the results by the tg_lastname field.
func ByTgLastname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgLastname, opts...).ToFunc()
}

// ByTgLanguage orders the results by the tg_language field.
func ByTgLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgLanguage, opts...).ToFunc()
}

// ByTgPicture orders the results by the tg_picture field.
func ByTgPicture(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgPicture, opts...).ToFunc()
}

// ByTgIsPremium orders the results by the tg_is_premium field.
func ByTgIsPremium(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgIsPremium, opts...).ToFunc()
}

// ByTgIsAllowPm orders the results by the tg_is_allow_pm field.
func ByTgIsAllowPm(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTgIsAllowPm, opts...).ToFunc()
}

// ByReferrerTgID orders the results by the referrer_tg_id field.
func ByReferrerTgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferrerTgID, opts...).ToFunc()
}

// ByWalletHdID orders the results by the wallet_hd_id field.
func ByWalletHdID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletHdID, opts...).ToFunc()
}

// ByAddressBounceable orders the results by the address_bounceable field.
func ByAddressBounceable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddressBounceable, opts...).ToFunc()
}

// ByAddressNonbounceable orders the results by the address_nonbounceable field.
func ByAddressNonbounceable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddressNonbounceable, opts...).ToFunc()
}

// ByTonBalance orders the results by the ton_balance field.
func ByTonBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTonBalance, opts...).ToFunc()
}

// ByTonBalanceLocked orders the results by the ton_balance_locked field.
func ByTonBalanceLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTonBalanceLocked, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCustomerChannelsCount orders the results by customer_channels count.
func ByCustomerChannelsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCustomerChannelsStep(), opts...)
	}
}

// ByCustomerChannels orders the results by customer_channels terms.
func ByCustomerChannels(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomerChannelsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCustomerBriefsCount orders the results by customer_briefs count.
func ByCustomerBriefsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCustomerBriefsStep(), opts...)
	}
}

// ByCustomerBriefs orders the results by customer_briefs terms.
func ByCustomerBriefs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomerBriefsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAdvertiserDealsCount orders the results by advertiser_deals count.
func ByAdvertiserDealsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAdvertiserDealsStep(), opts...)
	}
}

// ByAdvertiserDeals orders the results by advertiser_deals terms.
func ByAdvertiserDeals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdvertiserDealsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByManagedDealsCount orders the results by managed_deals count.
func ByManagedDealsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManagedDealsStep(), opts...)
	}
}

// ByManagedDeals orders the results by managed_deals terms.
func ByManagedDeals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagedDealsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCustomerChannelsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CustomerChannelsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CustomerChannelsTable, CustomerChannelsColumn),
	)
}
func newCustomerBriefsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CustomerBriefsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CustomerBriefsTable, CustomerBriefsColumn),
	)
}
func newAdvertiserDealsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdvertiserDealsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AdvertiserDealsTable, AdvertiserDealsColumn),
	)
}
func newManagedDealsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagedDealsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ManagedDealsTable, ManagedDealsColumn),
	)
}
