// Code generated by ent, DO NOT EDIT.

package customer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldUpdatedAt, v))
}

// TgID applies equality check predicate on the "tg_id" field. It's identical to TgIDEQ.
func TgID(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgID, v))
}

// TgUsername applies equality check predicate on the "tg_username" field. It's identical to TgUsernameEQ.
func TgUsername(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgUsername, v))
}

// TgFirstname applies equality check predicate on the "tg_firstname" field. It's identical to TgFirstnameEQ.
func TgFirstname(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgFirstname, v))
}

// TgLastname applies equality check predicate on the "tg_lastname" field. It's identical to TgLastnameEQ.
func TgLastname(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgLastname, v))
}

// TgLanguage applies equality check predicate on the "tg_language" field. It's identical to TgLanguageEQ.
func TgLanguage(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgLanguage, v))
}

// TgPicture applies equality check predicate on the "tg_picture" field. It's identical to TgPictureEQ.
func TgPicture(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgPicture, v))
}

// TgIsPremium applies equality check predicate on the "tg_is_premium" field. It's identical to TgIsPremiumEQ.
func TgIsPremium(v bool) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgIsPremium, v))
}

// TgIsAllowPm applies equality check predicate on the "tg_is_allow_pm" field. It's identical to TgIsAllowPmEQ.
func TgIsAllowPm(v bool) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgIsAllowPm, v))
}

// ReferrerTgID applies equality check predicate on the "referrer_tg_id" field. It's identical to ReferrerTgIDEQ.
func ReferrerTgID(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldReferrerTgID, v))
}

// WalletHdID applies equality check predicate on the "wallet_hd_id" field. It's identical to WalletHdIDEQ.
func WalletHdID(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldWalletHdID, v))
}

// AddressBounceable applies equality check predicate on the "address_bounceable" field. It's identical to AddressBounceableEQ.
func AddressBounceable(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldAddressBounceable, v))
}

// AddressNonbounceable applies equality check predicate on the "address_nonbounceable" field. It's identical to AddressNonbounceableEQ.
func AddressNonbounceable(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldAddressNonbounceable, v))
}

// TonBalance applies equality check predicate on the "ton_balance" field. It's identical to TonBalanceEQ.
func TonBalance(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTonBalance, v))
}

// TonBalanceLocked applies equality check predicate on the "ton_balance_locked" field. It's identical to TonBalanceLockedEQ.
func TonBalanceLocked(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTonBalanceLocked, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldUpdatedAt, v))
}

// TgIDEQ applies the EQ predicate on the "tg_id" field.
func TgIDEQ(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgID, v))
}

// TgIDNEQ applies the NEQ predicate on the "tg_id" field.
func TgIDNEQ(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTgID, v))
}

// TgIDIn applies the In predicate on the "tg_id" field.
func TgIDIn(vs ...int64) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldTgID, vs...))
}

// TgIDNotIn applies the NotIn predicate on the "tg_id" field.
func TgIDNotIn(vs ...int64) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldTgID, vs...))
}

// TgIDGT applies the GT predicate on the "tg_id" field.
func TgIDGT(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldTgID, v))
}

// TgIDGTE applies the GTE predicate on the "tg_id" field.
func TgIDGTE(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldTgID, v))
}

// TgIDLT applies the LT predicate on the "tg_id" field.
func TgIDLT(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldTgID, v))
}

// TgIDLTE applies the LTE predicate on the "tg_id" field.
func TgIDLTE(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldTgID, v))
}

// TgUsernameEQ applies the EQ predicate on the "tg_username" field.
func TgUsernameEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgUsername, v))
}

// TgUsernameNEQ applies the NEQ predicate on the "tg_username" field.
func TgUsernameNEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTgUsername, v))
}

// TgUsernameIn applies the In predicate on the "tg_username" field.
func TgUsernameIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldTgUsername, vs...))
}

// TgUsernameNotIn applies the NotIn predicate on the "tg_username" field.
func TgUsernameNotIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldTgUsername, vs...))
}

// TgUsernameGT applies the GT predicate on the "tg_username" field.
func TgUsernameGT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldTgUsername, v))
}

// TgUsernameGTE applies the GTE predicate on the "tg_username" field.
func TgUsernameGTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldTgUsername, v))
}

// TgUsernameLT applies the LT predicate on the "tg_username" field.
func TgUsernameLT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldTgUsername, v))
}

// TgUsernameLTE applies the LTE predicate on the "tg_username" field.
func TgUsernameLTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldTgUsername, v))
}

// TgUsernameContains applies the Contains predicate on the "tg_username" field.
func TgUsernameContains(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContains(FieldTgUsername, v))
}

// TgUsernameHasPrefix applies the HasPrefix predicate on the "tg_username" field.
func TgUsernameHasPrefix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasPrefix(FieldTgUsername, v))
}

// TgUsernameHasSuffix applies the HasSuffix predicate on the "tg_username" field.
func TgUsernameHasSuffix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasSuffix(FieldTgUsername, v))
}

// TgUsernameIsNil applies the IsNil predicate on the "tg_username" field.
func TgUsernameIsNil() predicate.Customer {
	return predicate.Customer(sql.FieldIsNull(FieldTgUsername))
}

// TgUsernameNotNil applies the NotNil predicate on the "tg_username" field.
func TgUsernameNotNil() predicate.Customer {
	return predicate.Customer(sql.FieldNotNull(FieldTgUsername))
}

// TgUsernameEqualFold applies the EqualFold predicate on the "tg_username" field.
func TgUsernameEqualFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEqualFold(FieldTgUsername, v))
}

// TgUsernameContainsFold applies the ContainsFold predicate on the "tg_username" field.
func TgUsernameContainsFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContainsFold(FieldTgUsername, v))
}

// TgFirstnameEQ applies the EQ predicate on the "tg_firstname" field.
func TgFirstnameEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgFirstname, v))
}

// TgFirstnameNEQ applies the NEQ predicate on the "tg_firstname" field.
func TgFirstnameNEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTgFirstname, v))
}

// TgFirstnameIn applies the In predicate on the "tg_firstname" field.
func TgFirstnameIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldTgFirstname, vs...))
}

// TgFirstnameNotIn applies the NotIn predicate on the "tg_firstname" field.
func TgFirstnameNotIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldTgFirstname, vs...))
}

// TgFirstnameGT applies the GT predicate on the "tg_firstname" field.
func TgFirstnameGT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldTgFirstname, v))
}

// TgFirstnameGTE applies the GTE predicate on the "tg_firstname" field.
func TgFirstnameGTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldTgFirstname, v))
}

// TgFirstnameLT applies the LT predicate on the "tg_firstname" field.
func TgFirstnameLT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldTgFirstname, v))
}

// TgFirstnameLTE applies the LTE predicate on the "tg_firstname" field.
func TgFirstnameLTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldTgFirstname, v))
}

// TgFirstnameContains applies the Contains predicate on the "tg_firstname" field.
func TgFirstnameContains(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContains(FieldTgFirstname, v))
}

// TgFirstnameHasPrefix applies the HasPrefix predicate on the "tg_firstname" field.
func TgFirstnameHasPrefix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasPrefix(FieldTgFirstname, v))
}

// TgFirstnameHasSuffix applies the HasSuffix predicate on the "tg_firstname" field.
func TgFirstnameHasSuffix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasSuffix(FieldTgFirstname, v))
}

// TgFirstnameIsNil applies the IsNil predicate on the "tg_firstname" field.
func TgFirstnameIsNil() predicate.Customer {
	return predicate.Customer(sql.FieldIsNull(FieldTgFirstname))
}

// TgFirstnameNotNil applies the NotNil predicate on the "tg_firstname" field.
func TgFirstnameNotNil() predicate.Customer {
	return predicate.Customer(sql.FieldNotNull(FieldTgFirstname))
}

// TgFirstnameEqualFold applies the EqualFold predicate on the "tg_firstname" field.
func TgFirstnameEqualFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEqualFold(FieldTgFirstname, v))
}

// TgFirstnameContainsFold applies the ContainsFold predicate on the "tg_firstname" field.
func TgFirstnameContainsFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContainsFold(FieldTgFirstname, v))
}

// TgLastnameEQ applies the EQ predicate on the "tg_lastname" field.
func TgLastnameEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgLastname, v))
}

// TgLastnameNEQ applies the NEQ predicate on the "tg_lastname" field.
func TgLastnameNEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTgLastname, v))
}

// TgLastnameIn applies the In predicate on the "tg_lastname" field.
func TgLastnameIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldTgLastname, vs...))
}

// TgLastnameNotIn applies the NotIn predicate on the "tg_lastname" field.
func TgLastnameNotIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldTgLastname, vs...))
}

// TgLastnameGT applies the GT predicate on the "tg_lastname" field.
func TgLastnameGT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldTgLastname, v))
}

// TgLastnameGTE applies the GTE predicate on the "tg_lastname" field.
func TgLastnameGTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldTgLastname, v))
}

// TgLastnameLT applies the LT predicate on the "tg_lastname" field.
func TgLastnameLT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldTgLastname, v))
}

// TgLastnameLTE applies the LTE predicate on the "tg_lastname" field.
func TgLastnameLTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldTgLastname, v))
}

// TgLastnameContains applies the Contains predicate on the "tg_lastname" field.
func TgLastnameContains(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContains(FieldTgLastname, v))
}

// TgLastnameHasPrefix applies the HasPrefix predicate on the "tg_lastname" field.
func TgLastnameHasPrefix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasPrefix(FieldTgLastname, v))
}

// TgLastnameHasSuffix applies the HasSuffix predicate on the "tg_lastname" field.
func TgLastnameHasSuffix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasSuffix(FieldTgLastname, v))
}

// TgLastnameIsNil applies the IsNil predicate on the "tg_lastname" field.
func TgLastnameIsNil() predicate.Customer {
	return predicate.Customer(sql.FieldIsNull(FieldTgLastname))
}

// TgLastnameNotNil applies the NotNil predicate on the "tg_lastname" field.
func TgLastnameNotNil() predicate.Customer {
	return predicate.Customer(sql.FieldNotNull(FieldTgLastname))
}

// TgLastnameEqualFold applies the EqualFold predicate on the "tg_lastname" field.
func TgLastnameEqualFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEqualFold(FieldTgLastname, v))
}

// TgLastnameContainsFold applies the ContainsFold predicate on the "tg_lastname" field.
func TgLastnameContainsFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContainsFold(FieldTgLastname, v))
}

// TgLanguageEQ applies the EQ predicate on the "tg_language" field.
func TgLanguageEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgLanguage, v))
}

// TgLanguageNEQ applies the NEQ predicate on the "tg_language" field.
func TgLanguageNEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTgLanguage, v))
}

// TgLanguageIn applies the In predicate on the "tg_language" field.
func TgLanguageIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldTgLanguage, vs...))
}

// TgLanguageNotIn applies the NotIn predicate on the "tg_language" field.
func TgLanguageNotIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldTgLanguage, vs...))
}

// TgLanguageGT applies the GT predicate on the "tg_language" field.
func TgLanguageGT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldTgLanguage, v))
}

// TgLanguageGTE applies the GTE predicate on the "tg_language" field.
func TgLanguageGTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldTgLanguage, v))
}

// TgLanguageLT applies the LT predicate on the "tg_language" field.
func TgLanguageLT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldTgLanguage, v))
}

// TgLanguageLTE applies the LTE predicate on the "tg_language" field.
func TgLanguageLTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldTgLanguage, v))
}

// TgLanguageContains applies the Contains predicate on the "tg_language" field.
func TgLanguageContains(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContains(FieldTgLanguage, v))
}

// TgLanguageHasPrefix applies the HasPrefix predicate on the "tg_language" field.
func TgLanguageHasPrefix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasPrefix(FieldTgLanguage, v))
}

// TgLanguageHasSuffix applies the HasSuffix predicate on the "tg_language" field.
func TgLanguageHasSuffix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasSuffix(FieldTgLanguage, v))
}

// TgLanguageIsNil applies the IsNil predicate on the "tg_language" field.
func TgLanguageIsNil() predicate.Customer {
	return predicate.Customer(sql.FieldIsNull(FieldTgLanguage))
}

// TgLanguageNotNil applies the NotNil predicate on the "tg_language" field.
func TgLanguageNotNil() predicate.Customer {
	return predicate.Customer(sql.FieldNotNull(FieldTgLanguage))
}

// TgLanguageEqualFold applies the EqualFold predicate on the "tg_language" field.
func TgLanguageEqualFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEqualFold(FieldTgLanguage, v))
}

// TgLanguageContainsFold applies the ContainsFold predicate on the "tg_language" field.
func TgLanguageContainsFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContainsFold(FieldTgLanguage, v))
}

// TgPictureEQ applies the EQ predicate on the "tg_picture" field.
func TgPictureEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgPicture, v))
}

// TgPictureNEQ applies the NEQ predicate on the "tg_picture" field.
func TgPictureNEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTgPicture, v))
}

// TgPictureIn applies the In predicate on the "tg_picture" field.
func TgPictureIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldTgPicture, vs...))
}

// TgPictureNotIn applies the NotIn predicate on the "tg_picture" field.
func TgPictureNotIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldTgPicture, vs...))
}

// TgPictureGT applies the GT predicate on the "tg_picture" field.
func TgPictureGT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldTgPicture, v))
}

// TgPictureGTE applies the GTE predicate on the "tg_picture" field.
func TgPictureGTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldTgPicture, v))
}

// TgPictureLT applies the LT predicate on the "tg_picture" field.
func TgPictureLT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldTgPicture, v))
}

// TgPictureLTE applies the LTE predicate on the "tg_picture" field.
func TgPictureLTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldTgPicture, v))
}

// TgPictureContains applies the Contains predicate on the "tg_picture" field.
func TgPictureContains(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContains(FieldTgPicture, v))
}

// TgPictureHasPrefix applies the HasPrefix predicate on the "tg_picture" field.
func TgPictureHasPrefix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasPrefix(FieldTgPicture, v))
}

// TgPictureHasSuffix applies the HasSuffix predicate on the "tg_picture" field.
func TgPictureHasSuffix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasSuffix(FieldTgPicture, v))
}

// TgPictureIsNil applies the IsNil predicate on the "tg_picture" field.
func TgPictureIsNil() predicate.Customer {
	return predicate.Customer(sql.FieldIsNull(FieldTgPicture))
}

// TgPictureNotNil applies the NotNil predicate on the "tg_picture" field.
func TgPictureNotNil() predicate.Customer {
	return predicate.Customer(sql.FieldNotNull(FieldTgPicture))
}

// TgPictureEqualFold applies the EqualFold predicate on the "tg_picture" field.
func TgPictureEqualFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEqualFold(FieldTgPicture, v))
}

// TgPictureContainsFold applies the ContainsFold predicate on the "tg_picture" field.
func TgPictureContainsFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContainsFold(FieldTgPicture, v))
}

// TgIsPremiumEQ applies the EQ predicate on the "tg_is_premium" field.
func TgIsPremiumEQ(v bool) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgIsPremium, v))
}

// TgIsPremiumNEQ applies the NEQ predicate on the "tg_is_premium" field.
func TgIsPremiumNEQ(v bool) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTgIsPremium, v))
}

// TgIsAllowPmEQ applies the EQ predicate on the "tg_is_allow_pm" field.
func TgIsAllowPmEQ(v bool) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTgIsAllowPm, v))
}

// TgIsAllowPmNEQ applies the NEQ predicate on the "tg_is_allow_pm" field.
func TgIsAllowPmNEQ(v bool) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTgIsAllowPm, v))
}

// ReferrerTgIDEQ applies the EQ predicate on the "referrer_tg_id" field.
func ReferrerTgIDEQ(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldReferrerTgID, v))
}

// ReferrerTgIDNEQ applies the NEQ predicate on the "referrer_tg_id" field.
func ReferrerTgIDNEQ(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldReferrerTgID, v))
}

// ReferrerTgIDIn applies the In predicate on the "referrer_tg_id" field.
func ReferrerTgIDIn(vs ...int64) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldReferrerTgID, vs...))
}

// ReferrerTgIDNotIn applies the NotIn predicate on the "referrer_tg_id" field.
func ReferrerTgIDNotIn(vs ...int64) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldReferrerTgID, vs...))
}

// ReferrerTgIDGT applies the GT predicate on the "referrer_tg_id" field.
func ReferrerTgIDGT(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldReferrerTgID, v))
}

// ReferrerTgIDGTE applies the GTE predicate on the "referrer_tg_id" field.
func ReferrerTgIDGTE(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldReferrerTgID, v))
}

// ReferrerTgIDLT applies the LT predicate on the "referrer_tg_id" field.
func ReferrerTgIDLT(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldReferrerTgID, v))
}

// ReferrerTgIDLTE applies the LTE predicate on the "referrer_tg_id" field.
func ReferrerTgIDLTE(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldReferrerTgID, v))
}

// ReferrerTgIDIsNil applies the IsNil predicate on the "referrer_tg_id" field.
func ReferrerTgIDIsNil() predicate.Customer {
	return predicate.Customer(sql.FieldIsNull(FieldReferrerTgID))
}

// ReferrerTgIDNotNil applies the NotNil predicate on the "referrer_tg_id" field.
func ReferrerTgIDNotNil() predicate.Customer {
	return predicate.Customer(sql.FieldNotNull(FieldReferrerTgID))
}

// WalletHdIDEQ applies the EQ predicate on the "wallet_hd_id" field.
func WalletHdIDEQ(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldWalletHdID, v))
}

// WalletHdIDNEQ applies the NEQ predicate on the "wallet_hd_id" field.
func WalletHdIDNEQ(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldWalletHdID, v))
}

// WalletHdIDIn applies the In predicate on the "wallet_hd_id" field.
func WalletHdIDIn(vs ...int64) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldWalletHdID, vs...))
}

// WalletHdIDNotIn applies the NotIn predicate on the "wallet_hd_id" field.
func WalletHdIDNotIn(vs ...int64) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldWalletHdID, vs...))
}

// WalletHdIDGT applies the GT predicate on the "wallet_hd_id" field.
func WalletHdIDGT(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldWalletHdID, v))
}

// WalletHdIDGTE applies the GTE predicate on the "wallet_hd_id" field.
func WalletHdIDGTE(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldWalletHdID, v))
}

// WalletHdIDLT applies the LT predicate on the "wallet_hd_id" field.
func WalletHdIDLT(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldWalletHdID, v))
}

// WalletHdIDLTE applies the LTE predicate on the "wallet_hd_id" field.
func WalletHdIDLTE(v int64) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldWalletHdID, v))
}

// WalletHdIDIsNil applies the IsNil predicate on the "wallet_hd_id" field.
func WalletHdIDIsNil() predicate.Customer {
	return predicate.Customer(sql.FieldIsNull(FieldWalletHdID))
}

// WalletHdIDNotNil applies the NotNil predicate on the "wallet_hd_id" field.
func WalletHdIDNotNil() predicate.Customer {
	return predicate.Customer(sql.FieldNotNull(FieldWalletHdID))
}

// AddressBounceableEQ applies the EQ predicate on the "address_bounceable" field.
func AddressBounceableEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldAddressBounceable, v))
}

// AddressBounceableNEQ applies the NEQ predicate on the "address_bounceable" field.
func AddressBounceableNEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldAddressBounceable, v))
}

// AddressBounceableIn applies the In predicate on the "address_bounceable" field.
func AddressBounceableIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldAddressBounceable, vs...))
}

// AddressBounceableNotIn applies the NotIn predicate on the "address_bounceable" field.
func AddressBounceableNotIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldAddressBounceable, vs...))
}

// AddressBounceableGT applies the GT predicate on the "address_bounceable" field.
func AddressBounceableGT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldAddressBounceable, v))
}

// AddressBounceableGTE applies the GTE predicate on the "address_bounceable" field.
func AddressBounceableGTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldAddressBounceable, v))
}

// AddressBounceableLT applies the LT predicate on the "address_bounceable" field.
func AddressBounceableLT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldAddressBounceable, v))
}

// AddressBounceableLTE applies the LTE predicate on the "address_bounceable" field.
func AddressBounceableLTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldAddressBounceable, v))
}

// AddressBounceableContains applies the Contains predicate on the "address_bounceable" field.
func AddressBounceableContains(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContains(FieldAddressBounceable, v))
}

// AddressBounceableHasPrefix applies the HasPrefix predicate on the "address_bounceable" field.
func AddressBounceableHasPrefix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasPrefix(FieldAddressBounceable, v))
}

// AddressBounceableHasSuffix applies the HasSuffix predicate on the "address_bounceable" field.
func AddressBounceableHasSuffix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasSuffix(FieldAddressBounceable, v))
}

// AddressBounceableIsNil applies the IsNil predicate on the "address_bounceable" field.
func AddressBounceableIsNil() predicate.Customer {
	return predicate.Customer(sql.FieldIsNull(FieldAddressBounceable))
}

// AddressBounceableNotNil applies the NotNil predicate on the "address_bounceable" field.
func AddressBounceableNotNil() predicate.Customer {
	return predicate.Customer(sql.FieldNotNull(FieldAddressBounceable))
}

// AddressBounceableEqualFold applies the EqualFold predicate on the "address_bounceable" field.
func AddressBounceableEqualFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEqualFold(FieldAddressBounceable, v))
}

// AddressBounceableContainsFold applies the ContainsFold predicate on the "address_bounceable" field.
func AddressBounceableContainsFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContainsFold(FieldAddressBounceable, v))
}

// AddressNonbounceableEQ applies the EQ predicate on the "address_nonbounceable" field.
func AddressNonbounceableEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldAddressNonbounceable, v))
}

// AddressNonbounceableNEQ applies the NEQ predicate on the "address_nonbounceable" field.
func AddressNonbounceableNEQ(v string) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldAddressNonbounceable, v))
}

// AddressNonbounceableIn applies the In predicate on the "address_nonbounceable" field.
func AddressNonbounceableIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldAddressNonbounceable, vs...))
}

// AddressNonbounceableNotIn applies the NotIn predicate on the "address_nonbounceable" field.
func AddressNonbounceableNotIn(vs ...string) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldAddressNonbounceable, vs...))
}

// AddressNonbounceableGT applies the GT predicate on the "address_nonbounceable" field.
func AddressNonbounceableGT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldAddressNonbounceable, v))
}

// AddressNonbounceableGTE applies the GTE predicate on the "address_nonbounceable" field.
func AddressNonbounceableGTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldAddressNonbounceable, v))
}

// AddressNonbounceableLT applies the LT predicate on the "address_nonbounceable" field.
func AddressNonbounceableLT(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldAddressNonbounceable, v))
}

// AddressNonbounceableLTE applies the LTE predicate on the "address_nonbounceable" field.
func AddressNonbounceableLTE(v string) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldAddressNonbounceable, v))
}

// AddressNonbounceableContains applies the Contains predicate on the "address_nonbounceable" field.
func AddressNonbounceableContains(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContains(FieldAddressNonbounceable, v))
}

// AddressNonbounceableHasPrefix applies the HasPrefix predicate on the "address_nonbounceable" field.
func AddressNonbounceableHasPrefix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasPrefix(FieldAddressNonbounceable, v))
}

// AddressNonbounceableHasSuffix applies the HasSuffix predicate on the "address_nonbounceable" field.
func AddressNonbounceableHasSuffix(v string) predicate.Customer {
	return predicate.Customer(sql.FieldHasSuffix(FieldAddressNonbounceable, v))
}

// AddressNonbounceableIsNil applies the IsNil predicate on the "address_nonbounceable" field.
func AddressNonbounceableIsNil() predicate.Customer {
	return predicate.Customer(sql.FieldIsNull(FieldAddressNonbounceable))
}

// AddressNonbounceableNotNil applies the NotNil predicate on the "address_nonbounceable" field.
func AddressNonbounceableNotNil() predicate.Customer {
	return predicate.Customer(sql.FieldNotNull(FieldAddressNonbounceable))
}

// AddressNonbounceableEqualFold applies the EqualFold predicate on the "address_nonbounceable" field.
func AddressNonbounceableEqualFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldEqualFold(FieldAddressNonbounceable, v))
}

// AddressNonbounceableContainsFold applies the ContainsFold predicate on the "address_nonbounceable" field.
func AddressNonbounceableContainsFold(v string) predicate.Customer {
	return predicate.Customer(sql.FieldContainsFold(FieldAddressNonbounceable, v))
}

// TonBalanceEQ applies the EQ predicate on the "ton_balance" field.
func TonBalanceEQ(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTonBalance, v))
}

// TonBalanceNEQ applies the NEQ predicate on the "ton_balance" field.
func TonBalanceNEQ(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTonBalance, v))
}

// TonBalanceIn applies the In predicate on the "ton_balance" field.
func TonBalanceIn(vs ...float64) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldTonBalance, vs...))
}

// TonBalanceNotIn applies the NotIn predicate on the "ton_balance" field.
func TonBalanceNotIn(vs ...float64) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldTonBalance, vs...))
}

// TonBalanceGT applies the GT predicate on the "ton_balance" field.
func TonBalanceGT(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldTonBalance, v))
}

// TonBalanceGTE applies the GTE predicate on the "ton_balance" field.
func TonBalanceGTE(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldTonBalance, v))
}

// TonBalanceLT applies the LT predicate on the "ton_balance" field.
func TonBalanceLT(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldTonBalance, v))
}

// TonBalanceLTE applies the LTE predicate on the "ton_balance" field.
func TonBalanceLTE(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldTonBalance, v))
}

// TonBalanceLockedEQ applies the EQ predicate on the "ton_balance_locked" field.
func TonBalanceLockedEQ(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldTonBalanceLocked, v))
}

// TonBalanceLockedNEQ applies the NEQ predicate on the "ton_balance_locked" field.
func TonBalanceLockedNEQ(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldTonBalanceLocked, v))
}

// TonBalanceLockedIn applies the In predicate on the "ton_balance_locked" field.
func TonBalanceLockedIn(vs ...float64) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldTonBalanceLocked, vs...))
}

// TonBalanceLockedNotIn applies the NotIn predicate on the "ton_balance_locked" field.
func TonBalanceLockedNotIn(vs ...float64) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldTonBalanceLocked, vs...))
}

// TonBalanceLockedGT applies the GT predicate on the "ton_balance_locked" field.
func TonBalanceLockedGT(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldTonBalanceLocked, v))
}

// TonBalanceLockedGTE applies the GTE predicate on the "ton_balance_locked" field.
func TonBalanceLockedGTE(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldTonBalanceLocked, v))
}

// TonBalanceLockedLT applies the LT predicate on the "ton_balance_locked" field.
func TonBalanceLockedLT(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldTonBalanceLocked, v))
}

// TonBalanceLockedLTE applies the LTE predicate on the "ton_balance_locked" field.
func TonBalanceLockedLTE(v float64) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldTonBalanceLocked, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int) predicate.Customer {
	return predicate.Customer(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int) predicate.Customer {
	return predicate.Customer(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int) predicate.Customer {
	return predicate.Customer(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int) predicate.Customer {
	return predicate.Customer(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int) predicate.Customer {
	return predicate.Customer(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int) predicate.Customer {
	return predicate.Customer(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int) predicate.Customer {
	return predicate.Customer(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int) predicate.Customer {
	return predicate.Customer(sql.FieldLTE(FieldStatus, v))
}

// HasCustomerChannels applies the HasEdge predicate on the "customer_channels" edge.
func HasCustomerChannels() predicate.Customer {
	return predicate.Customer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CustomerChannelsTable, CustomerChannelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerChannelsWith applies the HasEdge predicate on the "customer_channels" edge with a given conditions (other predicates).
func HasCustomerChannelsWith(preds ...predicate.CustomerChannel) predicate.Customer {
	return predicate.Customer(func(s *sql.Selector) {
		step := newCustomerChannelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomerBriefs applies the HasEdge predicate on the "customer_briefs" edge.
func HasCustomerBriefs() predicate.Customer {
	return predicate.Customer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CustomerBriefsTable, CustomerBriefsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerBriefsWith applies the HasEdge predicate on the "customer_briefs" edge with a given conditions (other predicates).
func HasCustomerBriefsWith(preds ...predicate.CustomerBrief) predicate.Customer {
	return predicate.Customer(func(s *sql.Selector) {
		step := newCustomerBriefsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAdvertiserDeals applies the HasEdge predicate on the "advertiser_deals" edge.
func HasAdvertiserDeals() predicate.Customer {
	return predicate.Customer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AdvertiserDealsTable, AdvertiserDealsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAdvertiserDealsWith applies the HasEdge predicate on the "advertiser_deals" edge with a given conditions (other predicates).
func HasAdvertiserDealsWith(preds ...predicate.Deal) predicate.Customer {
	return predicate.Customer(func(s *sql.Selector) {
		step := newAdvertiserDealsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasManagedDeals applies the HasEdge predicate on the "managed_deals" edge.
func HasManagedDeals() predicate.Customer {
	return predicate.Customer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ManagedDealsTable, ManagedDealsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasManagedDealsWith applies the HasEdge predicate on the "managed_deals" edge with a given conditions (other predicates).
func HasManagedDealsWith(preds ...predicate.Deal) predicate.Customer {
	return predicate.Customer(func(s *sql.Selector) {
		step := newManagedDealsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Customer) predicate.Customer {
	return predicate.Customer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Customer) predicate.Customer {
	return predicate.Customer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Customer) predicate.Customer {
	return predicate.Customer(sql.NotPredicates(p))
}
