-- +goose Up
CREATE TABLE bot_states (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id bigint NOT NULL UNIQUE,
                            deal_id uuid NULL,
                            state bigint NOT NULL DEFAULT 0,
                            data jsonb,
                            updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- +goose Down
DROP TABLE bot_states;