// Code generated by ent, DO NOT EDIT.

package botstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/wickedv43/TAM-backend/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BotState {
	return predicate.BotState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BotState {
	return predicate.BotState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BotState {
	return predicate.BotState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BotState {
	return predicate.BotState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BotState {
	return predicate.BotState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BotState {
	return predicate.BotState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BotState {
	return predicate.BotState(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldUserID, v))
}

// DealID applies equality check predicate on the "deal_id" field. It's identical to DealIDEQ.
func DealID(v uuid.UUID) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldDealID, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v int) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldState, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.BotState {
	return predicate.BotState(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.BotState {
	return predicate.BotState(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.BotState {
	return predicate.BotState(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.BotState {
	return predicate.BotState(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.BotState {
	return predicate.BotState(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.BotState {
	return predicate.BotState(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.BotState {
	return predicate.BotState(sql.FieldLTE(FieldUserID, v))
}

// DealIDEQ applies the EQ predicate on the "deal_id" field.
func DealIDEQ(v uuid.UUID) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldDealID, v))
}

// DealIDNEQ applies the NEQ predicate on the "deal_id" field.
func DealIDNEQ(v uuid.UUID) predicate.BotState {
	return predicate.BotState(sql.FieldNEQ(FieldDealID, v))
}

// DealIDIn applies the In predicate on the "deal_id" field.
func DealIDIn(vs ...uuid.UUID) predicate.BotState {
	return predicate.BotState(sql.FieldIn(FieldDealID, vs...))
}

// DealIDNotIn applies the NotIn predicate on the "deal_id" field.
func DealIDNotIn(vs ...uuid.UUID) predicate.BotState {
	return predicate.BotState(sql.FieldNotIn(FieldDealID, vs...))
}

// DealIDGT applies the GT predicate on the "deal_id" field.
func DealIDGT(v uuid.UUID) predicate.BotState {
	return predicate.BotState(sql.FieldGT(FieldDealID, v))
}

// DealIDGTE applies the GTE predicate on the "deal_id" field.
func DealIDGTE(v uuid.UUID) predicate.BotState {
	return predicate.BotState(sql.FieldGTE(FieldDealID, v))
}

// DealIDLT applies the LT predicate on the "deal_id" field.
func DealIDLT(v uuid.UUID) predicate.BotState {
	return predicate.BotState(sql.FieldLT(FieldDealID, v))
}

// DealIDLTE applies the LTE predicate on the "deal_id" field.
func DealIDLTE(v uuid.UUID) predicate.BotState {
	return predicate.BotState(sql.FieldLTE(FieldDealID, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v int) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v int) predicate.BotState {
	return predicate.BotState(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...int) predicate.BotState {
	return predicate.BotState(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...int) predicate.BotState {
	return predicate.BotState(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v int) predicate.BotState {
	return predicate.BotState(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v int) predicate.BotState {
	return predicate.BotState(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v int) predicate.BotState {
	return predicate.BotState(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v int) predicate.BotState {
	return predicate.BotState(sql.FieldLTE(FieldState, v))
}

// DataIsNil applies the IsNil predicate on the "data" field.
func DataIsNil() predicate.BotState {
	return predicate.BotState(sql.FieldIsNull(FieldData))
}

// DataNotNil applies the NotNil predicate on the "data" field.
func DataNotNil() predicate.BotState {
	return predicate.BotState(sql.FieldNotNull(FieldData))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BotState {
	return predicate.BotState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BotState {
	return predicate.BotState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BotState {
	return predicate.BotState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BotState {
	return predicate.BotState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BotState {
	return predicate.BotState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BotState {
	return predicate.BotState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BotState {
	return predicate.BotState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BotState {
	return predicate.BotState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BotState) predicate.BotState {
	return predicate.BotState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BotState) predicate.BotState {
	return predicate.BotState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BotState) predicate.BotState {
	return predicate.BotState(sql.NotPredicates(p))
}
